local LSM = LibStub("LibSharedMedia-3.0") 

-- ----- 
-- BACKGROUND 
-- ----- 
LSM:Register("background", "arrow_glow", [[Interface\Addons\CronixUIMedia\Media\background\arrow_glow.tga]]) 
LSM:Register("background", "Melli6px", [[Interface\Addons\CronixUIMedia\Media\background\Melli6px.tga]]) 

-- ----- 
--  BORDER 
-- ---- 
LSM:Register("border", "roth", [[Interface\Addons\CronixUIMedia\Media\border\roth.tga]]) 
LSM:Register("border", "SeerahScalloped", [[Interface\Addons\CronixUIMedia\Media\border\SeerahScalloped.tga]]) 

-- -----
--   FONT
-- -----
LSM:Register("font", "Cronix-Bold", [[Interface\Addons\CronixUIMedia\Media\font\Cronix-Bold.ttf]]) 
LSM:Register("font", "Cronix-Light", [[Interface\Addons\CronixUIMedia\Media\font\Cronix-Light.ttf]]) 
LSM:Register("font", "Cronix-Regular", [[Interface\Addons\CronixUIMedia\Media\font\Cronix-Regular.ttf]]) 
LSM:Register("font", "Cronix-Thin", [[Interface\Addons\CronixUIMedia\Media\font\Cronix-Thin.ttf]]) 
LSM:Register("font", "Cronix", [[Interface\Addons\CronixUIMedia\Media\font\Cronix.ttf]]) 

-- -----
--   SOUND
-- -----
LSM:Register("sound", "01", [[Interface\Addons\CronixUIMedia\Media\sound\01.ogg]]) 
LSM:Register("sound", "02", [[Interface\Addons\CronixUIMedia\Media\sound\02.ogg]]) 
LSM:Register("sound", "03", [[Interface\Addons\CronixUIMedia\Media\sound\03.ogg]]) 
LSM:Register("sound", "04", [[Interface\Addons\CronixUIMedia\Media\sound\04.ogg]]) 
LSM:Register("sound", "05", [[Interface\Addons\CronixUIMedia\Media\sound\05.ogg]]) 
LSM:Register("sound", "06", [[Interface\Addons\CronixUIMedia\Media\sound\06.ogg]]) 
LSM:Register("sound", "07", [[Interface\Addons\CronixUIMedia\Media\sound\07.ogg]]) 
LSM:Register("sound", "08", [[Interface\Addons\CronixUIMedia\Media\sound\08.ogg]]) 
LSM:Register("sound", "1", [[Interface\Addons\CronixUIMedia\Media\sound\1.ogg]]) 
LSM:Register("sound", "10", [[Interface\Addons\CronixUIMedia\Media\sound\10.ogg]]) 
LSM:Register("sound", "2", [[Interface\Addons\CronixUIMedia\Media\sound\2.ogg]]) 
LSM:Register("sound", "3", [[Interface\Addons\CronixUIMedia\Media\sound\3.ogg]]) 
LSM:Register("sound", "4", [[Interface\Addons\CronixUIMedia\Media\sound\4.ogg]]) 
LSM:Register("sound", "5", [[Interface\Addons\CronixUIMedia\Media\sound\5.ogg]]) 
LSM:Register("sound", "6", [[Interface\Addons\CronixUIMedia\Media\sound\6.ogg]]) 
LSM:Register("sound", "7", [[Interface\Addons\CronixUIMedia\Media\sound\7.ogg]]) 
LSM:Register("sound", "8", [[Interface\Addons\CronixUIMedia\Media\sound\8.ogg]]) 
LSM:Register("sound", "9", [[Interface\Addons\CronixUIMedia\Media\sound\9.ogg]]) 
LSM:Register("sound", "Add", [[Interface\Addons\CronixUIMedia\Media\sound\Add.ogg]]) 
LSM:Register("sound", "Adds", [[Interface\Addons\CronixUIMedia\Media\sound\Adds.ogg]]) 
LSM:Register("sound", "AoE", [[Interface\Addons\CronixUIMedia\Media\sound\AoE.ogg]]) 
LSM:Register("sound", "Assist", [[Interface\Addons\CronixUIMedia\Media\sound\Assist.ogg]]) 
LSM:Register("sound", "Avoid", [[Interface\Addons\CronixUIMedia\Media\sound\Avoid.ogg]]) 
LSM:Register("sound", "Back", [[Interface\Addons\CronixUIMedia\Media\sound\Back.ogg]]) 
LSM:Register("sound", "Backup", [[Interface\Addons\CronixUIMedia\Media\sound\Backup.ogg]]) 
LSM:Register("sound", "Bait", [[Interface\Addons\CronixUIMedia\Media\sound\Bait.ogg]]) 
LSM:Register("sound", "Bark", [[Interface\Addons\CronixUIMedia\Media\sound\Bark.ogg]]) 
LSM:Register("sound", "barrel", [[Interface\Addons\CronixUIMedia\Media\sound\barrel.ogg]]) 
LSM:Register("sound", "Beam", [[Interface\Addons\CronixUIMedia\Media\sound\Beam.ogg]]) 
LSM:Register("sound", "Blade", [[Interface\Addons\CronixUIMedia\Media\sound\Blade.ogg]]) 
LSM:Register("sound", "Bleed", [[Interface\Addons\CronixUIMedia\Media\sound\Bleed.ogg]]) 
LSM:Register("sound", "Bloodlust", [[Interface\Addons\CronixUIMedia\Media\sound\Bloodlust.ogg]]) 
LSM:Register("sound", "Blue", [[Interface\Addons\CronixUIMedia\Media\sound\Blue.ogg]]) 
LSM:Register("sound", "BoP", [[Interface\Addons\CronixUIMedia\Media\sound\BoP.ogg]]) 
LSM:Register("sound", "Boss", [[Interface\Addons\CronixUIMedia\Media\sound\Boss.ogg]]) 
LSM:Register("sound", "Break", [[Interface\Addons\CronixUIMedia\Media\sound\Break.ogg]]) 
LSM:Register("sound", "Buff", [[Interface\Addons\CronixUIMedia\Media\sound\Buff.ogg]]) 
LSM:Register("sound", "Buffed", [[Interface\Addons\CronixUIMedia\Media\sound\Buffed.ogg]]) 
LSM:Register("sound", "Bullet", [[Interface\Addons\CronixUIMedia\Media\sound\Bullet.ogg]]) 
LSM:Register("sound", "Cage", [[Interface\Addons\CronixUIMedia\Media\sound\Cage.ogg]]) 
LSM:Register("sound", "CC", [[Interface\Addons\CronixUIMedia\Media\sound\CC.ogg]]) 
LSM:Register("sound", "CD", [[Interface\Addons\CronixUIMedia\Media\sound\CD.ogg]]) 
LSM:Register("sound", "Center", [[Interface\Addons\CronixUIMedia\Media\sound\Center.ogg]]) 
LSM:Register("sound", "Chain", [[Interface\Addons\CronixUIMedia\Media\sound\Chain.ogg]]) 
LSM:Register("sound", "chains", [[Interface\Addons\CronixUIMedia\Media\sound\chains.ogg]]) 
LSM:Register("sound", "charge soon", [[Interface\Addons\CronixUIMedia\Media\sound\charge soon.ogg]]) 
LSM:Register("sound", "Charge", [[Interface\Addons\CronixUIMedia\Media\sound\Charge.ogg]]) 
LSM:Register("sound", "Clear", [[Interface\Addons\CronixUIMedia\Media\sound\Clear.ogg]]) 
LSM:Register("sound", "Collect", [[Interface\Addons\CronixUIMedia\Media\sound\Collect.ogg]]) 
LSM:Register("sound", "Cross", [[Interface\Addons\CronixUIMedia\Media\sound\Cross.ogg]]) 
LSM:Register("sound", "Curse", [[Interface\Addons\CronixUIMedia\Media\sound\Curse.ogg]]) 
LSM:Register("sound", "Dance", [[Interface\Addons\CronixUIMedia\Media\sound\Dance.ogg]]) 
LSM:Register("sound", "Debuff", [[Interface\Addons\CronixUIMedia\Media\sound\Debuff.ogg]]) 
LSM:Register("sound", "Disease", [[Interface\Addons\CronixUIMedia\Media\sound\Disease.ogg]]) 
LSM:Register("sound", "Dispell", [[Interface\Addons\CronixUIMedia\Media\sound\Dispell.ogg]]) 
LSM:Register("sound", "Dodge", [[Interface\Addons\CronixUIMedia\Media\sound\Dodge.ogg]]) 
LSM:Register("sound", "dont jump", [[Interface\Addons\CronixUIMedia\Media\sound\dont jump.ogg]]) 
LSM:Register("sound", "Dont Move", [[Interface\Addons\CronixUIMedia\Media\sound\Dont Move.ogg]]) 
LSM:Register("sound", "Dot", [[Interface\Addons\CronixUIMedia\Media\sound\Dot.ogg]]) 
LSM:Register("sound", "Drop", [[Interface\Addons\CronixUIMedia\Media\sound\Drop.ogg]]) 
LSM:Register("sound", "Duck", [[Interface\Addons\CronixUIMedia\Media\sound\Duck.ogg]]) 
LSM:Register("sound", "enrage", [[Interface\Addons\CronixUIMedia\Media\sound\enrage.ogg]]) 
LSM:Register("sound", "Enter", [[Interface\Addons\CronixUIMedia\Media\sound\Enter.ogg]]) 
LSM:Register("sound", "Escort", [[Interface\Addons\CronixUIMedia\Media\sound\Escort.ogg]]) 
LSM:Register("sound", "Exit", [[Interface\Addons\CronixUIMedia\Media\sound\Exit.ogg]]) 
LSM:Register("sound", "Fixate", [[Interface\Addons\CronixUIMedia\Media\sound\Fixate.ogg]]) 
LSM:Register("sound", "Front", [[Interface\Addons\CronixUIMedia\Media\sound\Front.ogg]]) 
LSM:Register("sound", "frontal", [[Interface\Addons\CronixUIMedia\Media\sound\frontal.ogg]]) 
LSM:Register("sound", "Gate", [[Interface\Addons\CronixUIMedia\Media\sound\Gate.ogg]]) 
LSM:Register("sound", "Gather", [[Interface\Addons\CronixUIMedia\Media\sound\Gather.ogg]]) 
LSM:Register("sound", "go away", [[Interface\Addons\CronixUIMedia\Media\sound\go away.ogg]]) 
LSM:Register("sound", "Green", [[Interface\Addons\CronixUIMedia\Media\sound\Green.ogg]]) 
LSM:Register("sound", "Healcd", [[Interface\Addons\CronixUIMedia\Media\sound\Healcd.ogg]]) 
LSM:Register("sound", "Hide", [[Interface\Addons\CronixUIMedia\Media\sound\Hide.ogg]]) 
LSM:Register("sound", "High Energy", [[Interface\Addons\CronixUIMedia\Media\sound\High Energy.ogg]]) 
LSM:Register("sound", "High Stacks", [[Interface\Addons\CronixUIMedia\Media\sound\High Stacks.ogg]]) 
LSM:Register("sound", "Immunity", [[Interface\Addons\CronixUIMedia\Media\sound\Immunity.ogg]]) 
LSM:Register("sound", "In", [[Interface\Addons\CronixUIMedia\Media\sound\In.ogg]]) 
LSM:Register("sound", "Info", [[Interface\Addons\CronixUIMedia\Media\sound\Info.ogg]]) 
LSM:Register("sound", "Innervate", [[Interface\Addons\CronixUIMedia\Media\sound\Innervate.ogg]]) 
LSM:Register("sound", "Intermission", [[Interface\Addons\CronixUIMedia\Media\sound\Intermission.ogg]]) 
LSM:Register("sound", "Interrupt", [[Interface\Addons\CronixUIMedia\Media\sound\Interrupt.ogg]]) 
LSM:Register("sound", "Invisibility", [[Interface\Addons\CronixUIMedia\Media\sound\Invisibility.ogg]]) 
LSM:Register("sound", "Jump", [[Interface\Addons\CronixUIMedia\Media\sound\Jump.ogg]]) 
LSM:Register("sound", "kick", [[Interface\Addons\CronixUIMedia\Media\sound\kick.ogg]]) 
LSM:Register("sound", "Knock", [[Interface\Addons\CronixUIMedia\Media\sound\Knock.ogg]]) 
LSM:Register("sound", "knockback", [[Interface\Addons\CronixUIMedia\Media\sound\knockback.ogg]]) 
LSM:Register("sound", "Left", [[Interface\Addons\CronixUIMedia\Media\sound\Left.ogg]]) 
LSM:Register("sound", "Linked", [[Interface\Addons\CronixUIMedia\Media\sound\Linked.ogg]]) 
LSM:Register("sound", "LoS", [[Interface\Addons\CronixUIMedia\Media\sound\LoS.ogg]]) 
LSM:Register("sound", "Magic", [[Interface\Addons\CronixUIMedia\Media\sound\Magic.ogg]]) 
LSM:Register("sound", "Mail", [[Interface\Addons\CronixUIMedia\Media\sound\Mail.ogg]]) 
LSM:Register("sound", "Main", [[Interface\Addons\CronixUIMedia\Media\sound\Main.ogg]]) 
LSM:Register("sound", "MC", [[Interface\Addons\CronixUIMedia\Media\sound\MC.ogg]]) 
LSM:Register("sound", "Melee", [[Interface\Addons\CronixUIMedia\Media\sound\Melee.ogg]]) 
LSM:Register("sound", "Move", [[Interface\Addons\CronixUIMedia\Media\sound\Move.ogg]]) 
LSM:Register("sound", "Next", [[Interface\Addons\CronixUIMedia\Media\sound\Next.ogg]]) 
LSM:Register("sound", "Nuke", [[Interface\Addons\CronixUIMedia\Media\sound\Nuke.ogg]]) 
LSM:Register("sound", "OnYou", [[Interface\Addons\CronixUIMedia\Media\sound\OnYou.ogg]]) 
LSM:Register("sound", "Orange", [[Interface\Addons\CronixUIMedia\Media\sound\Orange.ogg]]) 
LSM:Register("sound", "Orb", [[Interface\Addons\CronixUIMedia\Media\sound\Orb.ogg]]) 
LSM:Register("sound", "Out", [[Interface\Addons\CronixUIMedia\Media\sound\Out.ogg]]) 
LSM:Register("sound", "Overlap", [[Interface\Addons\CronixUIMedia\Media\sound\Overlap.ogg]]) 
LSM:Register("sound", "personal", [[Interface\Addons\CronixUIMedia\Media\sound\personal.ogg]]) 
LSM:Register("sound", "Phase2", [[Interface\Addons\CronixUIMedia\Media\sound\Phase2.ogg]]) 
LSM:Register("sound", "Phase3", [[Interface\Addons\CronixUIMedia\Media\sound\Phase3.ogg]]) 
LSM:Register("sound", "Physical", [[Interface\Addons\CronixUIMedia\Media\sound\Physical.ogg]]) 
LSM:Register("sound", "PI", [[Interface\Addons\CronixUIMedia\Media\sound\PI.ogg]]) 
LSM:Register("sound", "Poison", [[Interface\Addons\CronixUIMedia\Media\sound\Poison.ogg]]) 
LSM:Register("sound", "Positive", [[Interface\Addons\CronixUIMedia\Media\sound\Positive.ogg]]) 
LSM:Register("sound", "Pots", [[Interface\Addons\CronixUIMedia\Media\sound\Pots.ogg]]) 
LSM:Register("sound", "PS", [[Interface\Addons\CronixUIMedia\Media\sound\PS.ogg]]) 
LSM:Register("sound", "Pull", [[Interface\Addons\CronixUIMedia\Media\sound\Pull.ogg]]) 
LSM:Register("sound", "Purple", [[Interface\Addons\CronixUIMedia\Media\sound\Purple.ogg]]) 
LSM:Register("sound", "Push", [[Interface\Addons\CronixUIMedia\Media\sound\Push.ogg]]) 
LSM:Register("sound", "Range", [[Interface\Addons\CronixUIMedia\Media\sound\Range.ogg]]) 
LSM:Register("sound", "Ready", [[Interface\Addons\CronixUIMedia\Media\sound\Ready.ogg]]) 
LSM:Register("sound", "Red", [[Interface\Addons\CronixUIMedia\Media\sound\Red.ogg]]) 
LSM:Register("sound", "Reflect", [[Interface\Addons\CronixUIMedia\Media\sound\Reflect.ogg]]) 
LSM:Register("sound", "Right", [[Interface\Addons\CronixUIMedia\Media\sound\Right.ogg]]) 
LSM:Register("sound", "Ring", [[Interface\Addons\CronixUIMedia\Media\sound\Ring.ogg]]) 
LSM:Register("sound", "Root", [[Interface\Addons\CronixUIMedia\Media\sound\Root.ogg]]) 
LSM:Register("sound", "run", [[Interface\Addons\CronixUIMedia\Media\sound\run.ogg]]) 
LSM:Register("sound", "Sac", [[Interface\Addons\CronixUIMedia\Media\sound\Sac.ogg]]) 
LSM:Register("sound", "Seed", [[Interface\Addons\CronixUIMedia\Media\sound\Seed.ogg]]) 
LSM:Register("sound", "Selfcd", [[Interface\Addons\CronixUIMedia\Media\sound\Selfcd.ogg]]) 
LSM:Register("sound", "Sentry", [[Interface\Addons\CronixUIMedia\Media\sound\Sentry.ogg]]) 
LSM:Register("sound", "Shield", [[Interface\Addons\CronixUIMedia\Media\sound\Shield.ogg]]) 
LSM:Register("sound", "Side", [[Interface\Addons\CronixUIMedia\Media\sound\Side.ogg]]) 
LSM:Register("sound", "Soak", [[Interface\Addons\CronixUIMedia\Media\sound\Soak.ogg]]) 
LSM:Register("sound", "Soon", [[Interface\Addons\CronixUIMedia\Media\sound\Soon.ogg]]) 
LSM:Register("sound", "Spawn", [[Interface\Addons\CronixUIMedia\Media\sound\Spawn.ogg]]) 
LSM:Register("sound", "Spellsteal", [[Interface\Addons\CronixUIMedia\Media\sound\Spellsteal.ogg]]) 
LSM:Register("sound", "Split", [[Interface\Addons\CronixUIMedia\Media\sound\Split.ogg]]) 
LSM:Register("sound", "Spread", [[Interface\Addons\CronixUIMedia\Media\sound\Spread.ogg]]) 
LSM:Register("sound", "Stack", [[Interface\Addons\CronixUIMedia\Media\sound\Stack.ogg]]) 
LSM:Register("sound", "stop casting", [[Interface\Addons\CronixUIMedia\Media\sound\stop casting.ogg]]) 
LSM:Register("sound", "Stop", [[Interface\Addons\CronixUIMedia\Media\sound\Stop.ogg]]) 
LSM:Register("sound", "Stopcast", [[Interface\Addons\CronixUIMedia\Media\sound\Stopcast.ogg]]) 
LSM:Register("sound", "Switch", [[Interface\Addons\CronixUIMedia\Media\sound\Switch.ogg]]) 
LSM:Register("sound", "Targeted", [[Interface\Addons\CronixUIMedia\Media\sound\Targeted.ogg]]) 
LSM:Register("sound", "Taunt", [[Interface\Addons\CronixUIMedia\Media\sound\Taunt.ogg]]) 
LSM:Register("sound", "Throw", [[Interface\Addons\CronixUIMedia\Media\sound\Throw.ogg]]) 
LSM:Register("sound", "Thunder", [[Interface\Addons\CronixUIMedia\Media\sound\Thunder.ogg]]) 
LSM:Register("sound", "Totem", [[Interface\Addons\CronixUIMedia\Media\sound\Totem.ogg]]) 
LSM:Register("sound", "Transition", [[Interface\Addons\CronixUIMedia\Media\sound\Transition.ogg]]) 
LSM:Register("sound", "Trap", [[Interface\Addons\CronixUIMedia\Media\sound\Trap.ogg]]) 
LSM:Register("sound", "Turn", [[Interface\Addons\CronixUIMedia\Media\sound\Turn.ogg]]) 
LSM:Register("sound", "Wave", [[Interface\Addons\CronixUIMedia\Media\sound\Wave.ogg]]) 
LSM:Register("sound", "Winds", [[Interface\Addons\CronixUIMedia\Media\sound\Winds.ogg]]) 
LSM:Register("sound", "Yellow", [[Interface\Addons\CronixUIMedia\Media\sound\Yellow.ogg]]) 
LSM:Register("sound", "Zone", [[Interface\Addons\CronixUIMedia\Media\sound\Zone.ogg]]) 

-- -----
--   STATUSBAR
-- -----
LSM:Register("statusbar", "Cronix", [[Interface\Addons\CronixUIMedia\Media\statusbar\Cronix.tga]]) 
LSM:Register("statusbar", "Melli6px", [[Interface\Addons\CronixUIMedia\Media\statusbar\Melli6px.tga]]) 
