local addon, engine = ...
local CUI = select(2, ...):unpack()
local E,_,_,_,_ = unpack(ElvUI)

function CUI:ElvUIImport()
  E.db["actionbar"]["bar1"]["backdrop"] = true
  E.db["actionbar"]["bar1"]["backdropSpacing"] = 1
  E.db["actionbar"]["bar1"]["buttonSize"] = 28
  E.db["actionbar"]["bar1"]["buttonSpacing"] = 0
  E.db["actionbar"]["bar1"]["visibility"] = ""
  E.db["actionbar"]["bar10"]["mouseover"] = true
  E.db["actionbar"]["bar2"]["backdrop"] = true
  E.db["actionbar"]["bar2"]["backdropSpacing"] = 1
  E.db["actionbar"]["bar2"]["buttonSize"] = 28
  E.db["actionbar"]["bar2"]["buttonSpacing"] = 0
  E.db["actionbar"]["bar2"]["enabled"] = true
  E.db["actionbar"]["bar2"]["visibility"] = ""
  E.db["actionbar"]["bar3"]["backdrop"] = true
  E.db["actionbar"]["bar3"]["buttons"] = 12
  E.db["actionbar"]["bar3"]["buttonsPerRow"] = 1
  E.db["actionbar"]["bar3"]["enabled"] = false
  E.db["actionbar"]["bar3"]["point"] = "TOPRIGHT"
  E.db["actionbar"]["bar4"]["backdropSpacing"] = 1
  E.db["actionbar"]["bar4"]["buttonSize"] = 26
  E.db["actionbar"]["bar4"]["buttons"] = 6
  E.db["actionbar"]["bar5"]["backdrop"] = true
  E.db["actionbar"]["bar5"]["backdropSpacing"] = 1
  E.db["actionbar"]["bar5"]["buttonSize"] = 28
  E.db["actionbar"]["bar5"]["buttonSpacing"] = 0
  E.db["actionbar"]["bar5"]["buttons"] = 12
  E.db["actionbar"]["bar5"]["buttonsPerRow"] = 12
  E.db["actionbar"]["bar6"]["backdrop"] = true
  E.db["actionbar"]["bar6"]["backdropSpacing"] = 1
  E.db["actionbar"]["bar6"]["buttonSize"] = 26
  E.db["actionbar"]["bar6"]["buttons"] = 6
  E.db["actionbar"]["bar6"]["buttonsPerRow"] = 1
  E.db["actionbar"]["bar6"]["enabled"] = true
  E.db["actionbar"]["bar8"]["mouseover"] = true
  E.db["actionbar"]["bar9"]["mouseover"] = true
  E.db["actionbar"]["extraActionButton"]["alpha"] = 0.9
  E.db["actionbar"]["extraActionButton"]["scale"] = 0.75
  E.db["actionbar"]["lockActionBars"] = false
  E.db["actionbar"]["stanceBar"]["buttonSize"] = 28
  E.db["actionbar"]["stanceBar"]["enabled"] = false
  E.db["actionbar"]["transparent"] = true
  E.db["auras"]["buffs"]["countFontSize"] = 12
  E.db["auras"]["buffs"]["size"] = 24
  E.db["auras"]["buffs"]["sortDir"] = "+"
  E.db["auras"]["debuffs"]["countFontSize"] = 12
  E.db["auras"]["debuffs"]["size"] = 30
  E.db["bags"]["vendorGrays"]["enable"] = true
  E.db["chat"]["editBoxPosition"] = "ABOVE_CHAT"
  E.db["chat"]["font"] = "Designosaur"
  E.db["chat"]["fontOutline"] = "OUTLINE"
  E.db["chat"]["panelBackdrop"] = "LEFT"
  E.db["chat"]["panelHeight"] = 136
  E.db["chat"]["panelTabTransparency"] = true
  E.db["chat"]["panelWidth"] = 341
  E.db["chat"]["tabFont"] = "Accidental Presidency"
  E.db["chat"]["tabFontSize"] = 11
  E.db["convertPages"] = true
  E.db["cooldown"]["threshold"] = 4
  E.db["databars"]["azerite"]["height"] = 170
  E.db["databars"]["azerite"]["orientation"] = "VERTICAL"
  E.db["databars"]["azerite"]["width"] = 9
  E.db["databars"]["experience"]["height"] = 88
  E.db["databars"]["experience"]["orientation"] = "VERTICAL"
  E.db["databars"]["experience"]["width"] = 5
  E.db["databars"]["honor"]["enable"] = false
  E.db["databars"]["reputation"]["enable"] = true
  E.db["datatexts"]["fontSize"] = 4
  E.db["datatexts"]["panels"]["BuiMiddleDTPanel"]["left"] = "Durability"
  E.db["datatexts"]["panels"]["BuiMiddleDTPanel"]["middle"] = "Time"
  E.db["datatexts"]["panels"]["BuiMiddleDTPanel"]["right"] = "Gold"
  E.db["datatexts"]["panels"]["LeftChatDataPanel"]["left"] = "System"
  E.db["datatexts"]["panels"]["LeftChatDataPanel"]["middle"] = ""
  E.db["datatexts"]["panels"]["LeftChatDataPanel"]["right"] = "BuiMail"
  E.db["datatexts"]["panels"]["RightChatDataPanel"]["left"] = ""
  E.db["datatexts"]["panels"]["RightChatDataPanel"]["middle"] = ""
  E.db["datatexts"]["panels"]["RightChatDataPanel"]["right"] = ""
  E.db["datatexts"]["panels"]["RightMiniPanel"] = "Gold"
  E.db["general"]["bonusObjectivePosition"] = "RIGHT"
  E.db["general"]["bottomPanel"] = false
  E.db["general"]["minimap"]["icons"]["lfgEye"]["position"] = "BOTTOMLEFT"
  E.db["general"]["minimap"]["locationText"] = "HIDE"
  E.db["general"]["objectiveFrameHeight"] = 517
  E.db["general"]["stickyFrames"] = false
  E.db["general"]["talkingHeadFrameScale"] = 0.83
  E.db["general"]["valuecolor"]["b"] = 0.92
  E.db["general"]["valuecolor"]["g"] = 0.78
  E.db["general"]["valuecolor"]["r"] = 0.25
  E.db["movers"]["AlertFrameMover"] = "BOTTOM,ElvUIParent,BOTTOM,-17,312"
  E.db["movers"]["AltPowerBarMover"] = "TOP,ElvUIParent,TOP,0,-192"
  E.db["movers"]["ArenaHeaderMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-325,-337"
  E.db["movers"]["ArtifactBarMover"] = "BOTTOM,ElvUIParent,BOTTOM,296,0"
  E.db["movers"]["AzeriteBarMover"] = "BOTTOM,ElvUIParent,BOTTOM,182,0"
  E.db["movers"]["BNETMover"] = "TOPLEFT,ElvUIParent,TOPLEFT,327,-4"
  E.db["movers"]["BossButton"] = "BOTTOM,ElvUIParent,BOTTOM,-288,118"
  E.db["movers"]["BossHeaderMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-326,-263"
  E.db["movers"]["BuffsMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-180,-2"
  E.db["movers"]["BuiMiddleDtMover"] = "TOP,ElvUIParent,TOP,11,-6"
  E.db["movers"]["ClassBarMover"] = "BOTTOM,ElvUIParent,BOTTOM,-113,165"
  E.db["movers"]["DebuffsMover"] = "BOTTOMLEFT,UIParent,BOTTOMLEFT,389,269"
  E.db["movers"]["DigSiteProgressBarMover"] = "BOTTOM,ElvUIParent,BOTTOM,0,30"
  E.db["movers"]["DurabilityFrameMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-182,-128"
  E.db["movers"]["ElvAB_1"] = "BOTTOM,ElvUIParent,BOTTOM,0,52"
  E.db["movers"]["ElvAB_2"] = "BOTTOM,ElvUIParent,BOTTOM,0,79"
  E.db["movers"]["ElvAB_3"] = "BOTTOM,ElvUIParent,BOTTOM,-193,395"
  E.db["movers"]["ElvAB_4"] = "BOTTOM,ElvUIParent,BOTTOM,-242,1"
  E.db["movers"]["ElvAB_5"] = "BOTTOM,ElvUIParent,BOTTOM,0,108"
  E.db["movers"]["ElvAB_6"] = "BOTTOM,ElvUIParent,BOTTOM,272,0"
  E.db["movers"]["ElvUF_AssistMover"] = "TOPLEFT,ElvUIParent,BOTTOMLEFT,126,282"
  E.db["movers"]["ElvUF_BodyGuardMover"] = "BOTTOM,ElvUIParent,BOTTOM,0,25"
  E.db["movers"]["ElvUF_FocusCastbarMover"] = "BOTTOMLEFT,UIParent,BOTTOMLEFT,328,183"
  E.db["movers"]["ElvUF_FocusMover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,377,214"
  E.db["movers"]["ElvUF_PartyMover"] = "BOTTOMLEFT,UIParent,BOTTOMLEFT,526,386"
  E.db["movers"]["ElvUF_PetCastbarMover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,485,60"
  E.db["movers"]["ElvUF_PetMover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,485,76"
  E.db["movers"]["ElvUF_PlayerCastbarMover"] = "BOTTOM,UIParent,BOTTOM,12,384"
  E.db["movers"]["ElvUF_PlayerMover"] = "BOTTOM,ElvUIParent,BOTTOM,-273,197"
  E.db["movers"]["ElvUF_Raid1Mover"] = "BOTTOMLEFT,UIParent,BOTTOMLEFT,168,381"
  E.db["movers"]["ElvUF_Raid2Mover"] = "BOTTOMLEFT,UIParent,BOTTOMLEFT,371,382"
  E.db["movers"]["ElvUF_Raid3Mover"] = "BOTTOMLEFT,UIParent,BOTTOMLEFT,252,379"
  E.db["movers"]["ElvUF_RaidpetMover"] = "TOPLEFT,ElvUIParent,BOTTOMLEFT,4,720"
  E.db["movers"]["ElvUF_TankMover"] = "TOPLEFT,ElvUIParent,BOTTOMLEFT,4,282"
  E.db["movers"]["ElvUF_TargetCastbarMover"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-490,271"
  E.db["movers"]["ElvUF_TargetMover"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-491,199"
  E.db["movers"]["ElvUF_TargetTargetMover"] = "BOTTOM,ElvUIParent,BOTTOM,263,175"
  E.db["movers"]["ElvUIBagMover"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-440,1"
  E.db["movers"]["ExperienceBarMover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,448,2"
  E.db["movers"]["GMMover"] = "TOPLEFT,ElvUIParent,TOPLEFT,344,-56"
  E.db["movers"]["LeftChatMover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,0,0"
  E.db["movers"]["LootFrameMover"] = "TOPLEFT,ElvUIParent,TOPLEFT,172,-21"
  E.db["movers"]["LossControlMover"] = "BOTTOM,ElvUIParent,BOTTOM,-14,165"
  E.db["movers"]["MicrobarMover"] = "TOPLEFT,ElvUIParent,TOPLEFT,52,-81"
  E.db["movers"]["MinimapButtonAnchor"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,1,-206"
  E.db["movers"]["ObjectiveFrameMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-54,-236"
  E.db["movers"]["OzCooldownsMover"] = "BOTTOM,ElvUIParent,BOTTOM,0,400"
  E.db["movers"]["PetAB"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-450,27"
  E.db["movers"]["PlayerPowerBarMover"] = "BOTTOM,ElvUIParent,BOTTOM,-255,241"
  E.db["movers"]["RaidMarkerBarAnchor"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-378,0"
  E.db["movers"]["ReputationBarMover"] = "BOTTOM,ElvUIParent,BOTTOM,205,0"
  E.db["movers"]["RightChatMover"] = "BOTTOMRIGHT,UIParent,BOTTOMRIGHT,0,19"
  E.db["movers"]["ShiftAB"] = "TOPLEFT,ElvUIParent,BOTTOMLEFT,476,40"
  E.db["movers"]["SocialMenuMover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,0,60"
  E.db["movers"]["TalkingHeadFrameMover"] = "TOP,ElvUIParent,TOP,0,-133"
  E.db["movers"]["TargetPowerBarMover"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-254,204"
  E.db["movers"]["TooltipMover"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-4,238"
  E.db["movers"]["TorghastChoiceToggle"] = "BOTTOM,UIParent,BOTTOM,4,325"
  E.db["movers"]["TotemBarMover"] = "TOPLEFT,ElvUIParent,TOPLEFT,9,-19"
  E.db["movers"]["VehicleSeatMover"] = "TOPLEFT,ElvUIParent,TOPLEFT,137,-33"
  E.db["movers"]["ZoneAbility"] = "TOPLEFT,ElvUIParent,TOPLEFT,220,-26"
  E.db["nameplates"]["units"]["ENEMY_NPC"]["power"]["enable"] = true
  E.db["nameplates"]["visibility"]["enemy"]["guardians"] = true
  E.db["sle"]["media"]["fonts"]["zone"]["font"] = "2002 Bold"
  E.db["unitframe"]["colors"]["auraBarBuff"]["b"] = 0.91764503717422
  E.db["unitframe"]["colors"]["auraBarBuff"]["g"] = 0.77646887302399
  E.db["unitframe"]["colors"]["auraBarBuff"]["r"] = 0.24705828726292
  E.db["unitframe"]["colors"]["health_backdrop"]["b"] = 0.31372549019608
  E.db["unitframe"]["colors"]["health_backdrop"]["g"] = 0.31372549019608
  E.db["unitframe"]["colors"]["health_backdrop"]["r"] = 0.31372549019608
  E.db["unitframe"]["colors"]["healthclass"] = true
  E.db["unitframe"]["colors"]["transparentAurabars"] = true
  E.db["unitframe"]["font"] = "Big Noodle Titling"
  E.db["unitframe"]["fontOutline"] = "OUTLINE"
  E.db["unitframe"]["fontSize"] = 19
  E.db["unitframe"]["smoothbars"] = true
  E.db["unitframe"]["statusbar"] = "Minimalist"
  E.db["unitframe"]["units"]["arena"]["buffs"]["enable"] = false
  E.db["unitframe"]["units"]["arena"]["colorOverride"] = "FORCE_ON"
  E.db["unitframe"]["units"]["arena"]["debuffs"]["yOffset"] = 0
  E.db["unitframe"]["units"]["arena"]["enable"] = false
  E.db["unitframe"]["units"]["arena"]["health"]["text_format"] = ""
  E.db["unitframe"]["units"]["arena"]["height"] = 26
  E.db["unitframe"]["units"]["arena"]["width"] = 220
  E.db["unitframe"]["units"]["boss"]["buffs"]["enable"] = false
  E.db["unitframe"]["units"]["boss"]["castbar"]["width"] = 220
  E.db["unitframe"]["units"]["boss"]["customTexts"]["HP"]["attachTextTo"] = "HEALTH"
  E.db["unitframe"]["units"]["boss"]["customTexts"]["HP"]["enable"] = true
  E.db["unitframe"]["units"]["boss"]["customTexts"]["HP"]["font"] = "Big Noodle Titling"
  E.db["unitframe"]["units"]["boss"]["customTexts"]["HP"]["fontOutline"] = "OUTLINE"
  E.db["unitframe"]["units"]["boss"]["customTexts"]["HP"]["justifyH"] = "RIGHT"
  E.db["unitframe"]["units"]["boss"]["customTexts"]["HP"]["size"] = 16
  E.db["unitframe"]["units"]["boss"]["customTexts"]["HP"]["text_format"] = "[health:current-percent]"
  E.db["unitframe"]["units"]["boss"]["customTexts"]["HP"]["xOffset"] = 0
  E.db["unitframe"]["units"]["boss"]["customTexts"]["HP"]["yOffset"] = 22
  E.db["unitframe"]["units"]["boss"]["debuffs"]["anchorPoint"] = "TOPLEFT"
  E.db["unitframe"]["units"]["boss"]["debuffs"]["xOffset"] = -75
  E.db["unitframe"]["units"]["boss"]["debuffs"]["yOffset"] = -20
  E.db["unitframe"]["units"]["boss"]["health"]["text_format"] = ""
  E.db["unitframe"]["units"]["boss"]["height"] = 23
  E.db["unitframe"]["units"]["boss"]["name"]["position"] = "LEFT"
  E.db["unitframe"]["units"]["boss"]["name"]["text_format"] = "[level] [classification] || [namecolor][name:medium]"
  E.db["unitframe"]["units"]["boss"]["name"]["yOffset"] = 20
  E.db["unitframe"]["units"]["boss"]["power"]["text_format"] = ""
  E.db["unitframe"]["units"]["boss"]["spacing"] = 56
  E.db["unitframe"]["units"]["boss"]["width"] = 220
  E.db["unitframe"]["units"]["focus"]["castbar"]["height"] = 28
  E.db["unitframe"]["units"]["focus"]["castbar"]["width"] = 223
  E.db["unitframe"]["units"]["focus"]["height"] = 50
  E.db["unitframe"]["units"]["focus"]["width"] = 177
  E.db["unitframe"]["units"]["party"]["buffs"]["perrow"] = 3
  E.db["unitframe"]["units"]["party"]["customTexts"]["HP"]["attachTextTo"] = "Frame"
  E.db["unitframe"]["units"]["party"]["customTexts"]["HP"]["enable"] = false
  E.db["unitframe"]["units"]["party"]["customTexts"]["HP"]["font"] = "Big Noodle Titling"
  E.db["unitframe"]["units"]["party"]["customTexts"]["HP"]["fontOutline"] = "OUTLINE"
  E.db["unitframe"]["units"]["party"]["customTexts"]["HP"]["justifyH"] = "RIGHT"
  E.db["unitframe"]["units"]["party"]["customTexts"]["HP"]["size"] = 14
  E.db["unitframe"]["units"]["party"]["customTexts"]["HP"]["text_format"] = "[health:percent]"
  E.db["unitframe"]["units"]["party"]["customTexts"]["HP"]["xOffset"] = -19
  E.db["unitframe"]["units"]["party"]["customTexts"]["HP"]["yOffset"] = 5
  E.db["unitframe"]["units"]["party"]["customTexts"]["name font party frame"]["attachTextTo"] = "Health"
  E.db["unitframe"]["units"]["party"]["customTexts"]["name font party frame"]["enable"] = false
  E.db["unitframe"]["units"]["party"]["customTexts"]["name font party frame"]["font"] = "Big Noodle Titling"
  E.db["unitframe"]["units"]["party"]["customTexts"]["name font party frame"]["fontOutline"] = "OUTLINE"
  E.db["unitframe"]["units"]["party"]["customTexts"]["name font party frame"]["justifyH"] = "CENTER"
  E.db["unitframe"]["units"]["party"]["customTexts"]["name font party frame"]["size"] = 12
  E.db["unitframe"]["units"]["party"]["customTexts"]["name font party frame"]["text_format"] = "[name:veryshort][health:percent]"
  E.db["unitframe"]["units"]["party"]["customTexts"]["name font party frame"]["xOffset"] = 0
  E.db["unitframe"]["units"]["party"]["customTexts"]["name font party frame"]["yOffset"] = 0
  E.db["unitframe"]["units"]["party"]["debuffs"]["enable"] = false
  E.db["unitframe"]["units"]["party"]["debuffs"]["perrow"] = 3
  E.db["unitframe"]["units"]["party"]["debuffs"]["sizeOverride"] = 25
  E.db["unitframe"]["units"]["party"]["growthDirection"] = "DOWN_RIGHT"
  E.db["unitframe"]["units"]["party"]["health"]["position"] = "BOTTOM"
  E.db["unitframe"]["units"]["party"]["health"]["text_format"] = "[healthcolor][health:deficit]"
  E.db["unitframe"]["units"]["party"]["health"]["xOffset"] = 0
  E.db["unitframe"]["units"]["party"]["health"]["yOffset"] = 2
  E.db["unitframe"]["units"]["party"]["height"] = 43
  E.db["unitframe"]["units"]["party"]["horizontalSpacing"] = 2
  E.db["unitframe"]["units"]["party"]["infoPanel"]["height"] = 12
  E.db["unitframe"]["units"]["party"]["name"]["position"] = "BOTTOM"
  E.db["unitframe"]["units"]["party"]["name"]["text_format"] = "[name:veryshort]"
  E.db["unitframe"]["units"]["party"]["name"]["xOffset"] = 1
  E.db["unitframe"]["units"]["party"]["name"]["yOffset"] = 11
  E.db["unitframe"]["units"]["party"]["orientation"] = "MIDDLE"
  E.db["unitframe"]["units"]["party"]["portrait"]["camDistanceScale"] = 1
  E.db["unitframe"]["units"]["party"]["power"]["enable"] = false
  E.db["unitframe"]["units"]["party"]["power"]["position"] = "BOTTOMRIGHT"
  E.db["unitframe"]["units"]["party"]["power"]["text_format"] = ""
  E.db["unitframe"]["units"]["party"]["power"]["yOffset"] = 2
  E.db["unitframe"]["units"]["party"]["rdebuffs"]["size"] = 22
  E.db["unitframe"]["units"]["party"]["roleIcon"]["size"] = 12
  E.db["unitframe"]["units"]["party"]["verticalSpacing"] = 1
  E.db["unitframe"]["units"]["party"]["width"] = 101
  E.db["unitframe"]["units"]["pet"]["castbar"]["height"] = 12
  E.db["unitframe"]["units"]["pet"]["castbar"]["icon"] = false
  E.db["unitframe"]["units"]["pet"]["castbar"]["iconAttached"] = false
  E.db["unitframe"]["units"]["pet"]["castbar"]["width"] = 125
  E.db["unitframe"]["units"]["pet"]["customTexts"]["Pet Name"]["attachTextTo"] = "HEALTH"
  E.db["unitframe"]["units"]["pet"]["customTexts"]["Pet Name"]["enable"] = true
  E.db["unitframe"]["units"]["pet"]["customTexts"]["Pet Name"]["font"] = "Big Noodle Titling"
  E.db["unitframe"]["units"]["pet"]["customTexts"]["Pet Name"]["fontOutline"] = "OUTLINE"
  E.db["unitframe"]["units"]["pet"]["customTexts"]["Pet Name"]["justifyH"] = "CENTER"
  E.db["unitframe"]["units"]["pet"]["customTexts"]["Pet Name"]["size"] = 15
  E.db["unitframe"]["units"]["pet"]["customTexts"]["Pet Name"]["text_format"] = "[name:medium]"
  E.db["unitframe"]["units"]["pet"]["customTexts"]["Pet Name"]["xOffset"] = 0
  E.db["unitframe"]["units"]["pet"]["customTexts"]["Pet Name"]["yOffset"] = 2
  E.db["unitframe"]["units"]["pet"]["height"] = 25
  E.db["unitframe"]["units"]["pet"]["name"]["text_format"] = ""
  E.db["unitframe"]["units"]["pet"]["width"] = 125
  E.db["unitframe"]["units"]["player"]["aurabar"]["enable"] = false
  E.db["unitframe"]["units"]["player"]["castbar"]["enable"] = false
  E.db["unitframe"]["units"]["player"]["castbar"]["height"] = 22
  E.db["unitframe"]["units"]["player"]["castbar"]["tickColor"]["a"] = 0.80000001192093
  E.db["unitframe"]["units"]["player"]["castbar"]["width"] = 358
  E.db["unitframe"]["units"]["player"]["customTexts"]["[namecolor][name:medium] [difficultycolor][smartlevel] [shortclassification]"]["attachTextTo"] = "Frame"
  E.db["unitframe"]["units"]["player"]["customTexts"]["[namecolor][name:medium] [difficultycolor][smartlevel] [shortclassification]"]["enable"] = true
  E.db["unitframe"]["units"]["player"]["customTexts"]["[namecolor][name:medium] [difficultycolor][smartlevel] [shortclassification]"]["font"] = "Homespun"
  E.db["unitframe"]["units"]["player"]["customTexts"]["[namecolor][name:medium] [difficultycolor][smartlevel] [shortclassification]"]["fontOutline"] = "MONOCHROMEOUTLINE"
  E.db["unitframe"]["units"]["player"]["customTexts"]["[namecolor][name:medium] [difficultycolor][smartlevel] [shortclassification]"]["justifyH"] = "CENTER"
  E.db["unitframe"]["units"]["player"]["customTexts"]["[namecolor][name:medium] [difficultycolor][smartlevel] [shortclassification]"]["size"] = 18
  E.db["unitframe"]["units"]["player"]["customTexts"]["[namecolor][name:medium] [difficultycolor][smartlevel] [shortclassification]"]["text_format"] = "[namecolor][name:medium]"
  E.db["unitframe"]["units"]["player"]["customTexts"]["[namecolor][name:medium] [difficultycolor][smartlevel] [shortclassification]"]["xOffset"] = 0
  E.db["unitframe"]["units"]["player"]["customTexts"]["[namecolor][name:medium] [difficultycolor][smartlevel] [shortclassification]"]["yOffset"] = 0
  E.db["unitframe"]["units"]["player"]["customTexts"]["helth"]["attachTextTo"] = "Health"
  E.db["unitframe"]["units"]["player"]["customTexts"]["helth"]["enable"] = true
  E.db["unitframe"]["units"]["player"]["customTexts"]["helth"]["font"] = "Big Noodle Titling"
  E.db["unitframe"]["units"]["player"]["customTexts"]["helth"]["fontOutline"] = "OUTLINE"
  E.db["unitframe"]["units"]["player"]["customTexts"]["helth"]["justifyH"] = "CENTER"
  E.db["unitframe"]["units"]["player"]["customTexts"]["helth"]["size"] = 16
  E.db["unitframe"]["units"]["player"]["customTexts"]["helth"]["text_format"] = "[healthcolor][health:current]"
  E.db["unitframe"]["units"]["player"]["customTexts"]["helth"]["xOffset"] = -101
  E.db["unitframe"]["units"]["player"]["customTexts"]["helth"]["yOffset"] = 16
  E.db["unitframe"]["units"]["player"]["customTexts"]["mana"]["attachTextTo"] = "Health"
  E.db["unitframe"]["units"]["player"]["customTexts"]["mana"]["enable"] = true
  E.db["unitframe"]["units"]["player"]["customTexts"]["mana"]["font"] = "Big Noodle Titling"
  E.db["unitframe"]["units"]["player"]["customTexts"]["mana"]["fontOutline"] = "OUTLINE"
  E.db["unitframe"]["units"]["player"]["customTexts"]["mana"]["justifyH"] = "CENTER"
  E.db["unitframe"]["units"]["player"]["customTexts"]["mana"]["size"] = 16
  E.db["unitframe"]["units"]["player"]["customTexts"]["mana"]["text_format"] = "[powercolor][power:percent]"
  E.db["unitframe"]["units"]["player"]["customTexts"]["mana"]["xOffset"] = -101
  E.db["unitframe"]["units"]["player"]["customTexts"]["mana"]["yOffset"] = -37
  E.db["unitframe"]["units"]["player"]["customTexts"]["saadad"]["attachTextTo"] = "Health"
  E.db["unitframe"]["units"]["player"]["customTexts"]["saadad"]["enable"] = false
  E.db["unitframe"]["units"]["player"]["customTexts"]["saadad"]["font"] = "Big Noodle Titling"
  E.db["unitframe"]["units"]["player"]["customTexts"]["saadad"]["fontOutline"] = "OUTLINE"
  E.db["unitframe"]["units"]["player"]["customTexts"]["saadad"]["justifyH"] = "CENTER"
  E.db["unitframe"]["units"]["player"]["customTexts"]["saadad"]["size"] = 21
  E.db["unitframe"]["units"]["player"]["customTexts"]["saadad"]["text_format"] = ""
  E.db["unitframe"]["units"]["player"]["customTexts"]["saadad"]["xOffset"] = 0
  E.db["unitframe"]["units"]["player"]["customTexts"]["saadad"]["yOffset"] = 0
  E.db["unitframe"]["units"]["player"]["debuffs"]["enable"] = false
  E.db["unitframe"]["units"]["player"]["health"]["attachTextTo"] = "Frame"
  E.db["unitframe"]["units"]["player"]["health"]["position"] = "TOP"
  E.db["unitframe"]["units"]["player"]["health"]["text_format"] = ""
  E.db["unitframe"]["units"]["player"]["health"]["xOffset"] = 0
  E.db["unitframe"]["units"]["player"]["health"]["yOffset"] = -8
  E.db["unitframe"]["units"]["player"]["height"] = 74
  E.db["unitframe"]["units"]["player"]["name"]["attachTextTo"] = "Frame"
  E.db["unitframe"]["units"]["player"]["name"]["xOffset"] = 4
  E.db["unitframe"]["units"]["player"]["name"]["yOffset"] = -4
  E.db["unitframe"]["units"]["player"]["portrait"]["overlay"] = true
  E.db["unitframe"]["units"]["player"]["portrait"]["width"] = 77
  E.db["unitframe"]["units"]["player"]["power"]["attachTextTo"] = "Frame"
  E.db["unitframe"]["units"]["player"]["power"]["height"] = 21
  E.db["unitframe"]["units"]["player"]["power"]["hideonnpc"] = true
  E.db["unitframe"]["units"]["player"]["power"]["position"] = "BOTTOM"
  E.db["unitframe"]["units"]["player"]["power"]["strataAndLevel"]["frameLevel"] = 2
  E.db["unitframe"]["units"]["player"]["power"]["strataAndLevel"]["useCustomLevel"] = true
  E.db["unitframe"]["units"]["player"]["power"]["text_format"] = ""
  E.db["unitframe"]["units"]["player"]["power"]["xOffset"] = 0
  E.db["unitframe"]["units"]["player"]["power"]["yOffset"] = -80
  E.db["unitframe"]["units"]["raid1"]["customTexts"]["Name font"]["attachTextTo"] = "HEALTH"
  E.db["unitframe"]["units"]["raid1"]["customTexts"]["Name font"]["enable"] = true
  E.db["unitframe"]["units"]["raid1"]["customTexts"]["Name font"]["font"] = "Big Noodle Titling"
  E.db["unitframe"]["units"]["raid1"]["customTexts"]["Name font"]["fontOutline"] = "OUTLINE"
  E.db["unitframe"]["units"]["raid1"]["customTexts"]["Name font"]["justifyH"] = "LEFT"
  E.db["unitframe"]["units"]["raid1"]["customTexts"]["Name font"]["size"] = 12
  E.db["unitframe"]["units"]["raid1"]["customTexts"]["Name font"]["text_format"] = "[name:short]"
  E.db["unitframe"]["units"]["raid1"]["customTexts"]["Name font"]["xOffset"] = 16
  E.db["unitframe"]["units"]["raid1"]["customTexts"]["Name font"]["yOffset"] = -11
  E.db["unitframe"]["units"]["raid1"]["customTexts"]["health font raid fram"]["attachTextTo"] = "Health"
  E.db["unitframe"]["units"]["raid1"]["customTexts"]["health font raid fram"]["enable"] = true
  E.db["unitframe"]["units"]["raid1"]["customTexts"]["health font raid fram"]["font"] = "Big Noodle Titling"
  E.db["unitframe"]["units"]["raid1"]["customTexts"]["health font raid fram"]["fontOutline"] = "OUTLINE"
  E.db["unitframe"]["units"]["raid1"]["customTexts"]["health font raid fram"]["justifyH"] = "CENTER"
  E.db["unitframe"]["units"]["raid1"]["customTexts"]["health font raid fram"]["size"] = 16
  E.db["unitframe"]["units"]["raid1"]["customTexts"]["health font raid fram"]["text_format"] = "[health:percent]"
  E.db["unitframe"]["units"]["raid1"]["customTexts"]["health font raid fram"]["xOffset"] = 0
  E.db["unitframe"]["units"]["raid1"]["customTexts"]["health font raid fram"]["yOffset"] = 5
  E.db["unitframe"]["units"]["raid1"]["debuffs"]["sizeOverride"] = 25
  E.db["unitframe"]["units"]["raid1"]["growthDirection"] = "DOWN_RIGHT"
  E.db["unitframe"]["units"]["raid1"]["health"]["position"] = "BOTTOMLEFT"
  E.db["unitframe"]["units"]["raid1"]["health"]["text_format"] = ""
  E.db["unitframe"]["units"]["raid1"]["health"]["xOffset"] = -80
  E.db["unitframe"]["units"]["raid1"]["height"] = 43
  E.db["unitframe"]["units"]["raid1"]["horizontalSpacing"] = 2
  E.db["unitframe"]["units"]["raid1"]["name"]["attachTextTo"] = "Frame"
  E.db["unitframe"]["units"]["raid1"]["name"]["position"] = "BOTTOM"
  E.db["unitframe"]["units"]["raid1"]["name"]["text_format"] = ""
  E.db["unitframe"]["units"]["raid1"]["name"]["xOffset"] = 16
  E.db["unitframe"]["units"]["raid1"]["numGroups"] = 6
  E.db["unitframe"]["units"]["raid1"]["portrait"]["camDistanceScale"] = 1
  E.db["unitframe"]["units"]["raid1"]["power"]["enable"] = false
  E.db["unitframe"]["units"]["raid1"]["rdebuffs"]["enable"] = false
  E.db["unitframe"]["units"]["raid1"]["rdebuffs"]["size"] = 22
  E.db["unitframe"]["units"]["raid1"]["roleIcon"]["size"] = 12
  E.db["unitframe"]["units"]["raid1"]["verticalSpacing"] = 1
  E.db["unitframe"]["units"]["raid1"]["width"] = 101
  E.db["unitframe"]["units"]["raid2"]["numGroups"] = 6
  E.db["unitframe"]["units"]["raid3"]["customTexts"]["Custom Name"]["attachTextTo"] = "HEALTH"
  E.db["unitframe"]["units"]["raid3"]["customTexts"]["Custom Name"]["enable"] = true
  E.db["unitframe"]["units"]["raid3"]["customTexts"]["Custom Name"]["font"] = "Big Noodle Titling"
  E.db["unitframe"]["units"]["raid3"]["customTexts"]["Custom Name"]["fontOutline"] = "OUTLINE"
  E.db["unitframe"]["units"]["raid3"]["customTexts"]["Custom Name"]["justifyH"] = "CENTER"
  E.db["unitframe"]["units"]["raid3"]["customTexts"]["Custom Name"]["size"] = 14
  E.db["unitframe"]["units"]["raid3"]["customTexts"]["Custom Name"]["text_format"] = "[namecolor][name:short]"
  E.db["unitframe"]["units"]["raid3"]["customTexts"]["Custom Name"]["xOffset"] = 0
  E.db["unitframe"]["units"]["raid3"]["customTexts"]["Custom Name"]["yOffset"] = 0
  E.db["unitframe"]["units"]["raid3"]["debuffs"]["sizeOverride"] = 25
  E.db["unitframe"]["units"]["raid3"]["growthDirection"] = "DOWN_RIGHT"
  E.db["unitframe"]["units"]["raid3"]["height"] = 46
  E.db["unitframe"]["units"]["raid3"]["horizontalSpacing"] = 2
  E.db["unitframe"]["units"]["raid3"]["name"]["attachTextTo"] = "Frame"
  E.db["unitframe"]["units"]["raid3"]["name"]["position"] = "BOTTOM"
  E.db["unitframe"]["units"]["raid3"]["name"]["text_format"] = ""
  E.db["unitframe"]["units"]["raid3"]["name"]["xOffset"] = 16
  E.db["unitframe"]["units"]["raid3"]["roleIcon"]["enable"] = true
  E.db["unitframe"]["units"]["raid3"]["roleIcon"]["size"] = 12
  E.db["unitframe"]["units"]["raid3"]["sortDir"] = "DESC"
  E.db["unitframe"]["units"]["raid3"]["verticalSpacing"] = 1
  E.db["unitframe"]["units"]["raid3"]["width"] = 75
  E.db["unitframe"]["units"]["raidpet"]["colorOverride"] = "FORCE_OFF"
  E.db["unitframe"]["units"]["raidpet"]["sortDir"] = "DESC"
  E.db["unitframe"]["units"]["raidpet"]["threatStyle"] = "ICONBOTTOM"
  E.db["unitframe"]["units"]["raidpet"]["visibility"] = "[group:raid] show; "
  E.db["unitframe"]["units"]["tank"]["targetsGroup"]["enable"] = false
  E.db["unitframe"]["units"]["target"]["aurabar"]["enable"] = false
  E.db["unitframe"]["units"]["target"]["buffs"]["sizeOverride"] = 30
  E.db["unitframe"]["units"]["target"]["customTexts"]["Class"]["attachTextTo"] = "Frame"
  E.db["unitframe"]["units"]["target"]["customTexts"]["Class"]["enable"] = true
  E.db["unitframe"]["units"]["target"]["customTexts"]["Class"]["font"] = "Homespun"
  E.db["unitframe"]["units"]["target"]["customTexts"]["Class"]["fontOutline"] = "MONOCHROMEOUTLINE"
  E.db["unitframe"]["units"]["target"]["customTexts"]["Class"]["justifyH"] = "CENTER"
  E.db["unitframe"]["units"]["target"]["customTexts"]["Class"]["size"] = 18
  E.db["unitframe"]["units"]["target"]["customTexts"]["Class"]["text_format"] = "[namecolor][name:medium]"
  E.db["unitframe"]["units"]["target"]["customTexts"]["Class"]["xOffset"] = 0
  E.db["unitframe"]["units"]["target"]["customTexts"]["Class"]["yOffset"] = 0
  E.db["unitframe"]["units"]["target"]["customTexts"]["health target frame"]["attachTextTo"] = "Health"
  E.db["unitframe"]["units"]["target"]["customTexts"]["health target frame"]["enable"] = true
  E.db["unitframe"]["units"]["target"]["customTexts"]["health target frame"]["font"] = "Big Noodle Titling"
  E.db["unitframe"]["units"]["target"]["customTexts"]["health target frame"]["fontOutline"] = "OUTLINE"
  E.db["unitframe"]["units"]["target"]["customTexts"]["health target frame"]["justifyH"] = "CENTER"
  E.db["unitframe"]["units"]["target"]["customTexts"]["health target frame"]["size"] = 16
  E.db["unitframe"]["units"]["target"]["customTexts"]["health target frame"]["text_format"] = "[healthcolor][health:current-percent]"
  E.db["unitframe"]["units"]["target"]["customTexts"]["health target frame"]["xOffset"] = -101
  E.db["unitframe"]["units"]["target"]["customTexts"]["health target frame"]["yOffset"] = 16
  E.db["unitframe"]["units"]["target"]["customTexts"]["mana"]["attachTextTo"] = "Health"
  E.db["unitframe"]["units"]["target"]["customTexts"]["mana"]["enable"] = true
  E.db["unitframe"]["units"]["target"]["customTexts"]["mana"]["font"] = "Big Noodle Titling"
  E.db["unitframe"]["units"]["target"]["customTexts"]["mana"]["fontOutline"] = "OUTLINE"
  E.db["unitframe"]["units"]["target"]["customTexts"]["mana"]["justifyH"] = "CENTER"
  E.db["unitframe"]["units"]["target"]["customTexts"]["mana"]["size"] = 16
  E.db["unitframe"]["units"]["target"]["customTexts"]["mana"]["text_format"] = "[powercolor][power:percent]"
  E.db["unitframe"]["units"]["target"]["customTexts"]["mana"]["xOffset"] = -101
  E.db["unitframe"]["units"]["target"]["customTexts"]["mana"]["yOffset"] = -37
  E.db["unitframe"]["units"]["target"]["debuffs"]["anchorPoint"] = "TOPLEFT"
  E.db["unitframe"]["units"]["target"]["debuffs"]["attachTo"] = "FRAME"
  E.db["unitframe"]["units"]["target"]["debuffs"]["maxDuration"] = 0
  E.db["unitframe"]["units"]["target"]["debuffs"]["sizeOverride"] = 30
  E.db["unitframe"]["units"]["target"]["health"]["attachTextTo"] = "Frame"
  E.db["unitframe"]["units"]["target"]["health"]["position"] = "TOP"
  E.db["unitframe"]["units"]["target"]["health"]["text_format"] = ""
  E.db["unitframe"]["units"]["target"]["health"]["xOffset"] = 0
  E.db["unitframe"]["units"]["target"]["health"]["yOffset"] = -8
  E.db["unitframe"]["units"]["target"]["height"] = 74
  E.db["unitframe"]["units"]["target"]["name"]["attachTextTo"] = "Frame"
  E.db["unitframe"]["units"]["target"]["name"]["text_format"] = ""
  E.db["unitframe"]["units"]["target"]["name"]["xOffset"] = 4
  E.db["unitframe"]["units"]["target"]["name"]["yOffset"] = -4
  E.db["unitframe"]["units"]["target"]["orientation"] = "LEFT"
  E.db["unitframe"]["units"]["target"]["portrait"]["overlay"] = true
  E.db["unitframe"]["units"]["target"]["portrait"]["width"] = 77
  E.db["unitframe"]["units"]["target"]["power"]["attachTextTo"] = "Frame"
  E.db["unitframe"]["units"]["target"]["power"]["height"] = 21
  E.db["unitframe"]["units"]["target"]["power"]["hideonnpc"] = true
  E.db["unitframe"]["units"]["target"]["power"]["position"] = "BOTTOM"
  E.db["unitframe"]["units"]["target"]["power"]["strataAndLevel"]["frameLevel"] = 2
  E.db["unitframe"]["units"]["target"]["power"]["strataAndLevel"]["useCustomLevel"] = true
  E.db["unitframe"]["units"]["target"]["power"]["text_format"] = ""
  E.db["unitframe"]["units"]["target"]["power"]["xOffset"] = 0
  E.db["unitframe"]["units"]["target"]["power"]["yOffset"] = -80
  E.db["unitframe"]["units"]["targettarget"]["customTexts"]["Name Bar"]["attachTextTo"] = "HEALTH"
  E.db["unitframe"]["units"]["targettarget"]["customTexts"]["Name Bar"]["enable"] = true
  E.db["unitframe"]["units"]["targettarget"]["customTexts"]["Name Bar"]["font"] = "Big Noodle Titling"
  E.db["unitframe"]["units"]["targettarget"]["customTexts"]["Name Bar"]["fontOutline"] = "OUTLINE"
  E.db["unitframe"]["units"]["targettarget"]["customTexts"]["Name Bar"]["justifyH"] = "CENTER"
  E.db["unitframe"]["units"]["targettarget"]["customTexts"]["Name Bar"]["size"] = 15
  E.db["unitframe"]["units"]["targettarget"]["customTexts"]["Name Bar"]["text_format"] = "[name:medium]"
  E.db["unitframe"]["units"]["targettarget"]["customTexts"]["Name Bar"]["xOffset"] = 0
  E.db["unitframe"]["units"]["targettarget"]["customTexts"]["Name Bar"]["yOffset"] = 2
  E.db["unitframe"]["units"]["targettarget"]["debuffs"]["enable"] = false
  E.db["unitframe"]["units"]["targettarget"]["health"]["yOffset"] = 25
  E.db["unitframe"]["units"]["targettarget"]["height"] = 25
  E.db["unitframe"]["units"]["targettarget"]["name"]["text_format"] = ""
  E.db["unitframe"]["units"]["targettarget"]["width"] = 125
  
    E:UpdateAll(true)
    PluginInstallStepComplete.message = "ElvUI Profiles Imported"
    PluginInstallStepComplete:Show()
    
    --[[
    ElvDB["profiles"]["CronixUI"] = CUI.ElvUIDump
    Elv.data:SetProfile("CronixUI")
    --disable the totem bar
    Elv.private["general"]["totemBar"] = false
    --set the UI scale to 0.71
    ElvDB["global"]["general"]["UIScale"] = 0.71

      --Evoker Empowered abilites fix. This will need to be removed at some point in the future
  --ElvUI/Blizz just needs to put out an update to fix this problem
    SetCVar('ActionButtonUseKeyDown', 1)
    ElvUI[1]:GetModule('ActionBars'):UpdateButtonSettings()
    SetCVar("empowerTapControls",1)

    --re-enabled the ElvUI incompatility warning
  --do it here so we know it wasn't on when we don't want the warning
  --but we know it'll be on for the user in the future even if they don't complete the installer.
	Elv.global.ignoreIncompatible = false
    PluginInstallStepComplete.message = "ElvUI Profiles Imported"
    PluginInstallStepComplete:Show()
    ]]--
end

function CUI:PlaterImport()
    --[[
    PlaterDB["profiles"]["CronixUI"] = CUI.PlaterDump
    name = UnitName("PLAYER")
    realm = GetRealmName()
    --if we overwrite the PlaterDB to add our profiles it will forget which profile to load
    --set the profile key manually so the correct profile is selected after a reload
    PlaterDB["profileKeys"][name.." - "..realm] = "CronixUI"

    PluginInstallStepComplete.message = "Plater Profile Imported"
    PluginInstallStepComplete:Show()
    ]]--
end
