-- GravityUI Default Settings
local ADDON_NAME, ns = ...

ns.Defaults = {
    profile = {
    general =     {
        themeColor =         {
            [1] = 0,
            [2] = 0.57254904508591,
            [3] = 0.98823535442352,
            [4] = 1,
        },
        themeBgColor = {
            [1] = 0.10196079313755,
            [2] = 0.10196079313755,
            [3] = 0.10196079313755,
            [4] = 0.94901961088181,
        },
        fontOutline = "OUTLINE",
        useClassColorTheme = false,
        font = "Gravity",
        fontSize = 12,
        uiScale = 0.64,
        castbarTicks = {
            disintegrate = {
                enableUUF = false,
                enableBCDM = false,
                tickWidth = 2,
                tickHeight = 0.6,
                tickColor = {1, 1, 1, 0.7},
            },
            mindflay = {
                enableUUF = false,
                enableBCDM = false,
                tickWidth = 2,
                tickHeight = 0.6,
                tickColor = {1, 1, 1, 0.7},
            },
        },
    },
    styling = {
        chatBubbles = {
            enabled = true,
            fontSize = 8,
            fontOutline = "OUTLINE",
        },

        skinReadyCheck = true,
        readyCheck = {
            enable = true, -- Using this alongside skinReadyCheck or instead? best to keep skinReadyCheck for now or alias it. 
            -- Actually, let's just put the color options here.
            disableThemeColorBackground = false,
            customBackgroundColor = { 0.1, 0.1, 0.1, 0.95 },
            disableThemeColorFont = false,
            customFontColor = { 1, 1, 1, 1 },
        },
        gamemenu = {
            enabled = true,
            showGravityButton = true,
            buttonFontSize = 14,
            useThemeColorBackground = nil, -- Removed
            disableThemeColorBackground = false,
            customBackgroundColor = { 0.1, 0.1, 0.1, 0.95 },
            useThemeColorFont = nil, -- Removed
            disableThemeColorFont = true,
            customFontColor = { 1, 1, 1, 1 },
        },
        keystone = {
            enabled = true, -- Toggles the skinning
            disableThemeColorBackground = false,
            customBackgroundColor = { 0.1, 0.1, 0.1, 0.95 },
            disableThemeColorFont = false,
            customFontColor = { 1, 1, 1, 1 },
        },
        powerBar = {
            enabled = true,
            position = {
                y = 229.16749572754,
                relPoint = "BOTTOM",
                point = "BOTTOM",
                x = 1.6666791439056,
            },
        },
        alerts = {
            enabled = true,
            alertPosition = {
                y = -86.665824890137,
                relPoint = "CENTER",
                point = "CENTER",
                x = -294.16616821289,
            },
            alertGrowDirection = "UP",
            toastPosition = nil,
            toastGrowDirection = "DOWN",
            alertYOffset = 0,
            toastYOffset = 0,
            disableThemeColorBackground = false,
            customBackgroundColor = { 0.1, 0.1, 0.1, 0.95 },
            disableThemeColorFont = false,
            customFontColor = { 1, 1, 1, 1 },
        },
        loot = {
            enabled = true,
            position = {
                y = 118.33337402344,
                relPoint = "CENTER",
                point = "CENTER",
                x = 299.16604614258,
            },
            lootUnderMouse = false,
            showTransmogMarkers = true,
            disableThemeColorBackground = false,
            customBackgroundColor = { 0.1, 0.1, 0.1, 0.95 },
            disableThemeColorFont = false,
            customFontColor = { 1, 1, 1, 1 },
        },
        lootRoll = {
            enabled = true,
            position = nil,
            growDirection = "DOWN",
            spacing = 6,
            maxFrames = 4,
            width = 320,
            height = 40, -- Increased default height for better visibility
            timerHeight = 8,
            texture = "Gravity Normal",
            enableBackgroundColor = false,
            backgroundColor = { 0, 0, 0, 0.5 },
            nameFont = "Gravity",
            nameFontSize = 12,
            nameFontOutline = "OUTLINE",
            nameFontColor = { 1, 1, 1, 1 },
        },
        lootResults = {
            enabled = true,
            disableThemeColorBackground = false,
            customBackgroundColor = { 0.1, 0.1, 0.1, 0.95 },
            disableThemeColorFont = false,
            customFontColor = { 1, 1, 1, 1 },
            size = nil,
        },
        character = {
            enabled = false,
        },
        objectives = {
            enabled = true,
            -- UI Settings
            width = 235, -- Standard Blizzard width approx
            height = 410,
            hideBorder = true,
            
            -- Skinning Settings
            objectiveTrackerSkinning = true, -- Master Enable
            backgroundOpacity = 0.8,
            
            -- Background Color
            disableThemeColorForBackground = false, -- Default: Use Theme
            customBackgroundColor = { 0, 0.5, 1, 1 },
            
            -- Header Font Color
            disableThemeColorForHeaderFont = false, -- Default: Use Theme
            customHeaderFontColor = { 1, 1, 1, 1 },
            
            -- Cosmetic Bar
            cosmeticBar = {
                enable = true,
                width = 4,
                height = 10,
                widthMode = "FIXED", 
                heightMode = "DYNAMIC",
                offsetX = -10,
                offsetY = 0,
                texture = "Gravity",
                border = "NONE",
                borderAlpha = 1,
                disableThemeColor = false,
                color = { 1, 0.82, 0, 1 },
            },
            
            backdrop = {
                enable = true,
                transparent = true,
                topLeftOffsetX = 0,
                topLeftOffsetY = 0,
                bottomRightOffsetX = 0,
                bottomRightOffsetY = 0,
            },
        },
        instanceFrames = {
            enabled = true,
            disableThemeColorBackground = false,
            customBackgroundColor = { 0.1, 0.1, 0.1, 0.95 },
            disableThemeColorBorder = false,
            customBorderColor = { 1, 1, 1, 1 },
        },
        xpRep = {
            enabled = true,
            width = 500,
            height = 14,
            texture = "Gravity",
            fontSize = 10,
            fontOutline = "OUTLINE",
            showXP = true,
            showRep = true,
            mouseover = false,
            alwaysHide = false,
            alwaysShowText = false,
            strata = "MEDIUM",
            xpColor = { 0.6, 0, 0.6, 1 },
            restedColor = { 0, 0.4, 0.9, 1 },
            repColor = { 0, 0.6, 0.1, 1 },
            position = {
                point = "TOP",
                relativePoint = "TOP",
                x = 0,
                y = -20,
            },
        },
    },
    raidWarnings = {
        enabled = true,
        showInGroup = true,
        showInRaid = true,
        soundEnabled = true,
        font = "Gravity",
        fontSize = 24,
        color = {1, 1, 0, 1},
        soundFile = "Sound\\Interface\\RaidWarning.ogg",
        x = 0,
        y = 150,
        events = {
            soulwell = true,
            ritual = true,
            feast = true,
            repair = true,
            magetable = true,
            portal = false, -- Default portals OFF
        },
        customSpells = {}, -- { [spellID] = "type" } e.g. { [12345] = "feast" }
    },
    interruptTracker = {
        enabled = true,
        width = 200,
        height = 20,
        spacing = 0,
        texture = "Gravity Normal",
        font = "Gravity",
        fontSize = 12,
        fontOutline = "OUTLINE",
        
        -- Colors
        useClassColor = false,   -- Priority 1 for Bar Color
        
        useThemeBarColor = false,    -- Priority 2 (if class color off)
        barColor = {0.129, 0.129, 0.129, 0.851}, -- Priority 3 (Custom) #212121D9

        useSpecificCooldownColor = true,
        cooldownTextColor = {1, 1, 1, 1},
        showReadyText = true,

        useClassColorText = true,   -- Priority 1 for Font (NEW)
        useThemeFontColor = false, -- Priority 2 for Font
        textColor = {1, 1, 1, 1},   -- Priority 3 (Custom)

        useClassColorBackdrop = false, -- Priority 1 for Background (NEW)
        useThemeBackdropColor = false, -- Priority 2 for Background
        backdropColor = {0.463, 0.463, 0.463, 0.851}, -- Priority 3 (Custom) #767676D9

        growDirection = "UP",
        x = 0, 
        y = 0,
        sayKick = false,
        sayKickText = "Interrupted %t!",
    },
    raidBuffs = {
        enabled = true,
        showOnlyInGroup = true,
        showOnlyInInstance = true,
        providerMode = false,
        hideLabelBar = true,
        iconSize = 32,
        labelFontSize = 12,
        labelTextColor = nil,
        position = {
            y = 0,
            relPoint = "TOPLEFT",
            point = "TOPLEFT",
            x = 170.50061035156,
        },
    },
    profileInfo =     {
        created = 0,
        lastModified = 0,
        description = "",
    },
    uiimprovements =     {
        marks =         {
            enabled = true,
            mouseover = true,
            hideBorder = false,
            showTimerBar = true, -- New: Ready Check / Pull Bar
            removeDashes = true, -- New: Clean up lines
            offsetX = 936,
            spacing = 2,
            useThemeColorBorder = true,
            offsetY = -100,
            borderColor =             {
                [1] = 0,
                [2] = 0,
                [3] = 0,
                [4] = 1,
            },
            size = 26,
        },

        -- combatFont removed
        character =         {
            inspectEnabled = true,
            statsTextColor =             {
                [1] = 0.953,
                [2] = 0.957,
                [3] = 0.965,
            },
            showInspectItemName = true,
            showInspectGems = true,
            enchantTextColor =             {
                [1] = 0,
                [2] = 0.57254904508591,
                [3] = 0.98823535442352,
                [4] = 1,
            },
            showInspectItemLevel = true,
            showInspectEnchants = true,
            headerColor =             {
                [1] = 0,
                [2] = 0.57254904508591,
                [3] = 0.98823535442352,
                [4] = 1,
            },
            showItemLevel = true,
            showItemName = true,
            headerTextSize = 14,
            showEnchants = true,
            enabled = true,
            useThemeBackground = true,
            panelBgColor =             {
                [1] = 0.1294117718935,
                [2] = 0.1294117718935,
                [3] = 0.1294117718935,
                [4] = 0.85111129283905,
            },
            secondaryStatFormat = "both",
            inspectSlotTextSize = 12,
            noEnchantTextColor =             {
                [1] = 0.5,
                [2] = 0.5,
                [3] = 0.5,
            },
            slotTextSize = 12,
            enchantClassColor = false,
            statsTextSize = 12,
            showTooltips = true,
            panelOpacity = 95,
            inspectPanelScale = 1,
            upgradeTrackColor =             {
                [1] = 0.98,
                [2] = 0.6,
                [3] = 0.35,
                [4] = 1,
            },
            panelScale = 0.85,
            showDurability = false,
            headerClassColor = false,
            showGems = true,
        },
        hideObjectiveTrackerInstanceTypes =         {
            mythicPlus = false,
            mythicDungeon = false,
            normalDungeon = false,
            followerDungeon = false,
            heroicDungeon = false,
            arena = false,
            raid = false,
            pvp = false,
        },
        tooltip =         {
            enabled = true,
            fontSize = 12,
            hideHealthBar = true,
            bgAlpha = 0.6,
            useThemeColor = false,
            showIDs = true,
            bgColor =             {
                [1] = 0,
                [2] = 0,
                [3] = 0,
                [4] = 1,
            },
            customStyle = true,
            anchorToCursor = false,
            combatKey = "SHIFT",
            classColorName = true,
            borderColor =             {
                [1] = 0,
                [2] = 0,
                [3] = 0,
                [4] = 1,
            },
            idColor =             {
                [1] = 1,
                [2] = 1,
                [3] = 1,
                [4] = 1,
            },
            hideInCombat = false,
            visibility =             {
                items = "SHOW",
                abilities = "SHOW",
                npcs = "SHOW",
                customTrackers = "SHOW",
                frames = "SHOW",
                cdm = "SHOW",
            },
            useThemeColorID = true,
        },



        combatTimer =         {
            backdropColor =             {
                [1] = 0,
                [2] = 0,
                [3] = 0,
                [4] = 0.6,
            },
            strata = "BACKGROUND",
            xOffset = 198,
            yOffset = -254,
            borderSize = 1,
            borderColor =             {
                [1] = 0,
                [2] = 0,
                [3] = 0,
                [4] = 1,
            },
            level = 50,
            enabled = true,
            onlyEncounter = false,
            width = 56,
            hideBorder = true,
            showBackdrop = true,
            useThemeColorText = true,
            useThemeColorBorder = true,
            height = 24,
            textAlign = "CENTER",
            fontSize = 14,
            textColor =             {
                [1] = 1,
                [2] = 1,
                [3] = 1,
                [4] = 1,
            },
        },
        deleteFix = true,
        deathReleaseProtection = true,


        hideFriendlyNPCNameplates = true,
        buffBorders =         {
            fontSize = 12,
            enableDebuffs = true,
            borderSize = 2,
            enableBuffs = true,
            hideDebuffFrame = false,
            hideBuffFrame = false,
        },

        spellQueueWindow = 150,
        chat =         {
            enabled = true,
            glass =             {
                bgColor =                 {
                    [1] = 0,
                    [2] = 0,
                    [3] = 0,
                    [4] = 1,
                },
                enabled = true,
                bgAlpha = 0.25,
            },
            hideTabs = false,
            tabs = {
                activeTab = {
                    useThemeColor = true,
                    customColor = {1, 0.8, 0, 1},
                    alpha = 0.9,
                    disableBox = false,
                    disableBackground = false,
                },
                inactiveTab = {
                    alpha = 0.7,
                },
            },
            fade =             {
                enabled = false,
                delay = 15,
            },
            copyButtonMode = "hover",
            hideButtons = true,
            urls =             {
                enabled = true,
                color =                 {
                    [1] = 0,
                    [2] = 0.75,
                    [3] = 1,
                    [4] = 1,
                },
            },
            unclamp = true,
            editBox =             {
                enabled = true,
                positionTop = false,
                offsetX = 0,
                bgAlpha = 0.6,
                height = 24,
                offsetY = -5,
                bgColor =                 {
                    [1] = 0,
                    [2] = 0,
                    [3] = 0,
                    [4] = 1,
                },
                width = 476,
            },
            timestamps =             {
                enabled = true,
                format = "24h",
                color =                 {
                    [1] = 0.7607843875885,
                    [2] = 0.77254909276962,
                    [3] = 0.73725491762161,
                    [4] = 1,
                },
            },
        },
        autoAcceptInvites = "off",
        hideWorldMapBlackout = true,

        autoAcceptQuest = true,
        fasterMovieSkip = true,

        quickSalvage =         {
            enabled = false,
            modifier = "ALT",
        },

        showDamageNumbers = true,
        autoRoleAccept = true,
        lfgQuickJoin = true,
        lfgQuickJoinRoles = { tank = false, healer = false, dps = true },
        autoRepair = "personal",
        hideRaidFrameManager = true,
        sellJunk = true,
        hideBuffCollapseButton = true,

        hideObjectiveTrackerAlways = false,
        mplusTeleportEnabled = true,
        autoInsertKey = true,
        hideErrorMessages = true,
        autoTurnInQuest = true,
        questHoldShift = true,
        hideFriendlyPlayerNameplates = true,
        autoCombatLog = false,
        autoCombatLogRaidNormal = false,
        autoCombatLogRaidHeroic = false,
        autoCombatLogRaidMythic = false,
        autoSelectGossip = false,
        fastAutoLoot = false,
        hideTalkingHead = false,
        muteTalkingHead = false,
        hideOnWorldQuestMinigame = true,
    },
    configPanelAlpha = 1,
    minimap =     {
        settingsPreview = false,
        showCraftingOrder = true,
        craftingConfig =         {
            scale = 1,
            offsetY = 90,
            point = "LEFT",
            offsetX = 0,
        },
        hideBlizzardBorder = true,
        zoneTextConfig =         {
            colorContested =             {
                [1] = 1,
                [2] = 0.7,
                [3] = 0,
            },
            fontSize = 15,
            allCaps = false,
            useBlizzardZoneColors = false,
            align = "CENTER",
            colorNormal =             {
                [1] = 1,
                [2] = 0.82,
                [3] = 0,
                [4] = 1,
            },
            colorArena =             {
                [1] = 1,
                [2] = 0.1,
                [3] = 0.1,
            },
            colorSanctuary =             {
                [1] = 0.41,
                [2] = 0.8,
                [3] = 0.94,
            },
            font = "Gravity",
            colorHostile =             {
                [1] = 1,
                [2] = 0.1,
                [3] = 0.1,
            },
            offsetX = 0,
            useThemeColor = true,
            colorFriendly =             {
                [1] = 0.1,
                [2] = 1,
                [3] = 0.1,
            },
            offsetY = -1,
            outline = "OUTLINE",
            monochrome = false,
        },
        datatext =         {
            enabled = true,
            fontSize = 13,
            fontColor =             {
                [1] = 1,
                [2] = 1,
                [3] = 1,
                [4] = 1,
            },
            slot1 =             {
                shortLabel = false,
                noLabel = false,
                offsetX = 0,
                offsetY = 0,
                content = "guild",
            },
            bgOpacity = 60,
            useThemeColor = true,
            slot3 =             {
                shortLabel = false,
                noLabel = false,
                offsetX = 0,
                offsetY = 0,
                content = "friends",
            },
            borderSize = 1,
            offsetX = 0,
            borderColor =             {
                [1] = 0,
                [2] = 0,
                [3] = 0,
                [4] = 1,
            },
            height = 25,
            offsetY = 0,
            useThemeColorBorder = false,
            slot2 =             {
                shortLabel = false,
                noLabel = true,
                offsetX = 0,
                offsetY = 0,
                content = "time",
            },
        },
        trackingConfig =         {
            scale = 1,
            offsetY = 0,
            point = "TOPLEFT",
            offsetX = 0,
        },
        lock = true,
        button =         {
            minimapPos = 220,
            hide = false,
        },
        size = 260,
        useThemeColorBorder = false,
        datatextExpanded = true,
        autoZoom = true,
        eyeExpanded = true,
        hideAddonButtons = true,
        showAddonCompartment = false,
        position =         {
            [1] = "TOPRIGHT",
            [2] = "TOPRIGHT",
            [3] = -9.1689233779907,
            [4] = -8.3333225250244,
        },
        fadeElements = true,
        zoomConfig =         {
            scale = 1,
            offsetY = -233,
            point = "TOPRIGHT",
            offsetX = -30.5,
        },
        shape = "SQUARE",
        showDifficulty = true,
        stylingExpanded = true,
        scale = 1,
        showMRT = true,
        showMissions = false,
        borderColor =         {
            [1] = 0,
            [2] = 0,
            [3] = 0,
            [4] = 1,
        },
        clockConfig =         {
            outline = "OUTLINE",
            fontSize = 12,
            point = "TOPRIGHT",
            align = "CENTER",
            monochrome = false,
            timeFormat = "local",
            font = "Gravity",
            offsetX = -116,
            color =             {
                [1] = 1,
                [2] = 1,
                [3] = 1,
                [4] = 1,
            },
            offsetY = -196.5,
            useClassColor = false,
            scale = 1,
        },
        elementsExpanded = true,
        borderSize = 1,
        showZoneText = true,
        mailConfig =         {
            scale = 1,
            offsetY = 0,
            offsetX = 0,
            point = "BOTTOMLEFT",
        },
        addonCompartmentConfig =         {
            scale = 1,
            offsetY = -113,
            point = "TOPRIGHT",
            offsetX = -1,
        },
        enabled = true,
        rotate = false,
        showZoomButtons = false,
        showCalendar = false,
        zoneExpanded = true,
        showPing = true,
        hideQuestBlobs = true,
        difficultyConfig =         {
            scale = 1,
            offsetY = -0.5,
            point = "TOPRIGHT",
            offsetX = 0,
        },
        showCoords = false,
        showTracking = true,
        showAccuracy = false,
        styleExpanded = true,
        calendarConfig =         {
            scale = 1,
            offsetY = -1,
            offsetX = -27.5,
            point = "TOPRIGHT",
        },
        showClock = false,
        showMail = true,
        coordsConfig =         {
            outline = "OUTLINE",
            fontSize = 12,
            point = "TOPRIGHT",
            align = "RIGHT",
            monochrome = false,
            font = "Gravity",
            offsetX = -114,
            color =             {
                [1] = 1,
                [2] = 1,
                [3] = 1,
                [4] = 1,
            },
            offsetY = -235,
            useClassColor = false,
            scale = 1,
        },
        useClassColorBorder = false,
        button = {
            hide = false,
            minimapPos = 220,
        },
        catcher = {
            enabled = true,
            masque = false,
            showIconBackground = true,
            fadeOutEnabled = false,
            fadeOutTime = 10,
            locked = false,
            mode = "ICON", -- "ICON" or "BAR"
            catcherIcon = "GravityUI",
            useThemeColor = true,
            customBackgroundColor = {0.1, 0.1, 0.1, 0.95},
            iconsPerRow = 4,
            iconSize = 30,
            growDirection = "DOWN", -- "DOWN", "UP", "LEFT", "RIGHT"
            customFrames = "", -- comma separated strings, e.g "BtwQuestsMinimapButton, WIM3MinimapButton"
            offsetX = 0,
            offsetY = 0,
            minimapPos = 200, -- Angle if mode is ICON
            catcherIconSize = 40,
            catcherBarWidth = 100,
            catcherBarHeight = 20,
            hardcodedHides = "", -- comma separated strings, e.g "_G.ExpansionLandingPageMinimapButton"
        },
        dungeonEye =         {
            enabled = true,
            corner = "BOTTOMLEFT",
            scale = 0.8,
            preview = false,
            offsetY = 0,
            offsetX = 1,
        },
        missionsConfig =         {
            scale = 1,
            offsetY = -235,
            point = "TOPRIGHT",
            offsetX = -114,
        },
        mrtConfig =         {
            scale = 1,
            offsetY = -28,
            point = "TOPRIGHT",
            offsetX = -28,
        },
        generalExpanded = true,
        posExpanded = false,
    },
    fpsBackup =     {
        entityLodDist = "7",
        lodObjectMinSize = "0",
        graphicsProjectedTextures = "1",
        doodadLodScale = "50",
        MSAAQuality = "0",
        LowLatencyMode = "3",
        maxFPSBk = "30",
        spellVisualDensityFilterSetting = "1",
        RenderScale = "0.83",
        rippleDetail = "0",
        graphicsLiquidDetail = "1",
        graphicsShadowQuality = "0",
        entityShadowFadeScale = "15",
        graphicsSpellDensity = "0",
        reflectionMode = "0",
        ResampleAlwaysSharpen = "1",
        terrainLodDist = "350",
        Gamma = "1.1",
        OutlineEngineMode = "1",
        vsync = "0",
        cameraDistanceMaxZoomFactor = "2.6",
        lodObjectCullSize = "35",
        lodObjectFadeScale = "50",
        graphicsGroundClutter = "0",
        cameraFov = "90",
        graphicsOutlineMode = "1",
        weatherDensity = "3",
        waterDetail = "1",
        horizonStart = "1000",
        ffxGlow = "0",
        horizonClip = "5000",
        groundEffectDist = "40",
        useTargetFPS = "0",
        ResampleSharpness = "0.2",
        graphicsViewDistance = "3",
        projectedTextures = "1",
        graphicsParticleDensity = "5",
        ffxAntiAliasingMode = "0",
        clusteredShading = "0",
        Contrast = "75",
        Brightness = "50",
        farclip = "5000",
        volumeFogLevel = "0",
        particulatesEnabled = "0",
        targetFPS = "61",
        maxFPS = "144",
        graphicsDepthEffects = "0",
        graphicsSSAO = "0",
        spellClutter = "1",
        GxApi = "D3D12",
        ResampleQuality = "3",
        graphicsComputeEffects = "0",
        graphicsQuality = "9",
        graphicsTextureResolution = "2",
        CameraReduceUnexpectedMovement = "1",
        graphicsEnvironmentDetail = "0",
        TerrainLodDiv = "512",
        physicsLevel = "1",
        textureFilteringMode = "5",
    },
-- Legacy QOL table removed
    datapanels =     {
        extraExpanded = true,
        minimapExpanded = true,
        initialized = false,
        custom = {},
        customExpanded = true,
    },
    screenindicators =     {
        petWarnings =         {
            enabled = true,
            fontSize = 28,
            xOffset = 0,
            yOffset = -100,
            petDeadWarning = true,
            useThemeColor = true,
            warningColor =             {
                [1] = 1,
                [2] = 1,
                [3] = 1,
                [4] = 1,
            },
            petAttackWarning = true,
            petAttackText = "*** PET NOT ATTACKING ***",
            petDeadText = "*** SUMMON PET ***",
            strata = "TOOLTIP",
        },
        petWarningsExpanded = true,
        combatStatus =         {
            enabled = true,
            fontSize = 14,
            leaveCombatColor =             {
                [1] = 1,
                [2] = 1,
                [3] = 1,
                [4] = 1,
            },
            fadeTime = 0.3,
            xOffset = 0,
            enterCombatColor =             {
                [1] = 0,
                [2] = 0.57254904508591,
                [3] = 0.98823535442352,
                [4] = 1,
            },
            displayTime = 0.8,
            yOffset = -20,
        },
        cursor =         {
            enabled = true,
            hideOutOfCombat = false,
            reticleSize = 10,
            outCombatAlpha = 1,
            offsetY = 0,
            reticleStyle = "dot",
            hideOnRightClick = false,
            customColor =             {
                [1] = 0,
                [2] = 0.75,
                [3] = 1,
                [4] = 1,
            },
            ringSize = 20,
            gcdReverse = false,
            offsetX = 0,
            useThemeColor = true,
            gcdFadeRing = 0.35,
            gcdEnabled = false,
            ringStyle = "standard",
            inCombatAlpha = 1,
        },
        cursorExpanded = true,
        crosshairExpanded = true,
        enabled = true,
        combatStatusExpanded = true,
        crosshair =         {
            strata = "HIGH",
            borderB = 0,
            customColor =             {
                [1] = 1,
                [2] = 0.949,
                [3] = 0,
                [4] = 1,
            },
            borderSize = 2,
            offsetX = 0,
            changeColorOnRange = true,
            size = 9,
            enabled = false,
            rangeColorInCombatOnly = false,
            outOfRangeColor =             {
                [1] = 1,
                [2] = 0.2,
                [3] = 0.2,
                [4] = 1,
            },
            thickness = 2,
            borderR = 0,
            borderG = 0,
            useThemeColor = false,
            borderA = 1,
            offsetY = 0,
            hideUntilOutOfRange = false,
            onlyInCombat = false,
        },
        afkScreen = {
            enabled = false,
            camTurnSpeed = 3,
            rotationDirection = 1, -- 1: Left, 2: Right, 3: Random
            useClassColor = true,
            useThemeColor = false,
            customColor = { 1, 1, 1, 1 },
            preventInAh = true,
            showCharacter = true,
            animationState = 0, -- Standard stand
            showRealm = false,
            showTitle = true,
            showGuild = true,
            showBrackets = true,
            showRank = false,
            displaySeconds = true,
            timeFormat = 1, -- 1: 24h, 2: 12h, 3: 12h no leading 0
            showAmPm = false,
            showTimer = true,
        },
    },
    main =     {
        showWelcome = true,
        showQuickSettings = true,
    },
    actionbars =     {
        bar5_vis = true,
        bar8_vis = true,
        global =         {
            countFontSize = 14,
            usabilityIndicator = true,
            macroNameFontSize = 10,
            keybindColor =             {
                [1] = 1,
                [2] = 1,
                [3] = 1,
                [4] = 1,
            },
            macroNameOffsetY = 2,
            showKeybinds = true,
            countOffsetY = 2,
            hideEmptyKeybinds = true,
            keybindAnchor = "TOPRIGHT",
            keybindOffsetX = 0,
            hideEmptySlots = false,
            keybindOffsetY = -2,
            showGloss = false,
            showCounts = true,
            countOffsetX = 0,
            showBorders = true,
            countColor =             {
                [1] = 1,
                [2] = 1,
                [3] = 1,
                [4] = 1,
            },
            backdropAlpha = 0.3,
            usabilityDesaturate = false,
            showBackdrop = true,
            macroNameOffsetX = 0,
            countAnchor = "BOTTOMRIGHT",
            macroNameAnchor = "BOTTOM",
            fastUsabilityUpdates = true,
            glossAlpha = 0.6,
            iconZoom = 0.06,
            showMacroNames = true,
            keybindFontSize = 12,
            macroNameColor =             {
                [1] = 1,
                [2] = 1,
                [3] = 1,
                [4] = 1,
            },
        },
        absExpanded = true,
        fadeExpanded = true,
        fade =         {
            enabled = true,
            fadeOutAlpha = 0,
            fadeOutDuration = 0.4,
            linkBars1to8 = false,
            fadeInDuration = 0.2,
            fadeOutDelay = 0.5,
            alwaysShowInCombat = false,
        },
        masterExpanded = true,
        extraExpanded = true,
        enabled = true,
        bars =         {
            bar3 =             {
                alwaysShow = false,
                overrideEnabled = false,
            },
            bar6 =             {
                alwaysShow = false,
                overrideEnabled = false,
            },
            extraActionButton =             {
                alwaysShow = true,
                position =                 {
                    y = 151.46852111816,
                    x = 334.50012207031,
                    point = "BOTTOM",
                    relativePoint = "BOTTOM",
                },
                scale = 1,
                overrideEnabled = false,
                hideArtwork = true,
            },
            bar2 =             {
                alwaysShow = false,
                overrideEnabled = false,
            },
            bar1 =             {
                alwaysShow = true,
                hidePageArrow = true,
                overrideEnabled = false,
            },
            bar8 =             {
                alwaysShow = true,
                overrideEnabled = false,
            },
            bar5 =             {
                alwaysShow = true,
                overrideEnabled = false,
            },
            stance =             {
                alwaysShow = false,
                overrideEnabled = false,
            },
            bar7 =             {
                alwaysShow = false,
                overrideEnabled = false,
            },
            pet =             {
                alwaysShow = false,
                overrideEnabled = false,
            },
            bags =             {
                alwaysShow = false,
                overrideEnabled = false,
            },
            zoneAbility =             {
                alwaysShow = true,
                scale = 1,
                overrideEnabled = false,
                hideArtwork = true,
            },
            microbar =             {
                alwaysShow = false,
                overrideEnabled = false,
            },
            bar4 =             {
                alwaysShow = true,
            },
        },
        bar7_vis = true,
        bar6_vis = true,
            guicdm = {
                enabled = true,
                fontSize = 12,
                anchor = "TOPRIGHT",
                offsetX = 0,
                offsetY = 0,
                color = {1, 1, 1, 1},
                utils = {
                    buttonGlow = false,
                    buttonGlowColor = {1, 0.9, 0, 1}, -- Default Yellow
                    hideKeybindText = false,
                },
                bars = {
                    essential = true,
                    utility = true,
                    custom = true,
                    additionalCustom = true,
                    trinket = true,
                    item = true,
                    itemSpell = true,
                },
                barStyles = {
                    essential = { fontSize = 12, color = {1, 1, 1, 1} },
                    utility = { fontSize = 12, color = {1, 1, 1, 1} },
                custom = { fontSize = 12, color = {1, 1, 1, 1} },
                additionalCustom = { fontSize = 12, color = {1, 1, 1, 1} },
                trinket = { fontSize = 12, color = {1, 1, 1, 1} },
                item = { fontSize = 12, color = {1, 1, 1, 1} },
                itemSpell = { fontSize = 12, color = {1, 1, 1, 1} },
            },
        },
        cdmCentering = {
            enabled = true,
            essential = true,
            utility = true,
        },
        cdmBuffbar = {
            enabled = true,
            -- Master
            texture = "Gravity Normal",
            height = 20,
            -- width removed
            fontSize = 12,
            font = "Gravity",

            
            -- Colors
            useThemeBackground = true,
            backgroundColor = {0, 0, 0, 0.5},
            useThemeColor = true,
            barColor = {0, 0.57, 0.98, 1},
            
            -- Icon
            iconSize = 20,
            iconBorderSize = 1,
            iconBorderColor = {0, 0, 0, 1},
            
            -- Spark
            sparkColor = {0.85, 0.85, 0.85, 1},
            
            -- Dynamic Positioning
            dynamicPositioning = false,
            growDirection = "DOWN", -- UP or DOWN
            spacing = 0,
            anchor = {point="CENTER", relativePoint="CENTER", x=0, y=0},
        },
    },
    skyriding =     {
        secondWindHeight = 20,
        speedFontSize = 11,
        useThemeColorSecondWind = false,
        rechargeColor =         {
            [1] = 0.40000003576279,
            [2] = 0.90196084976196,
            [3] = 1,
            [4] = 0.60000002384186,
        },
        vigorFontSize = 12,
        showSpeed = true,
        speedFormat = "PERCENT",
        segmentThickness = 1,
        offsetX = -0.000244140625,
        secondWindColor =         {
            [1] = 1,
            [2] = 0.80000007152557,
            [3] = 0.20000001788139,
            [4] = 1,
        },
        locked = false,
        fadeDelay = 1,
        secondWindMode = "MINIBAR",
        width = 286,
        enabled = true,
        fadeDuration = 0.3,
        segmentColor =         {
            [1] = 0,
            [2] = 0,
            [3] = 0,
            [4] = 0.5,
        },
        secondWindScale = 1,
        showSegments = true,
        barTexture = "Gravity v3",
        barColor =         {
            [1] = 0.20000001788139,
            [2] = 0.80000007152557,
            [3] = 1,
            [4] = 1,
        },
        vigorHeight = 20,
        showVigorText = true,
        secondWindBackgroundColor =         {
            [1] = 0.10196079313755,
            [2] = 0.10196079313755,
            [3] = 0.10196079313755,
            [4] = 0.80000001192093,
        },
        vigorTextFormat = "CURRENT",
        backgroundColor =         {
            [1] = 0.10196079313755,
            [2] = 0.10196079313755,
            [3] = 0.10196079313755,
            [4] = 0.80000001192093,
        },
        useThemeColorVigor = true,
        offsetY = -308.33227539062,
        visibility = "AUTO",
        showAbilityIcon = false,
    },
}
}
