-- GravityUI Default Settings
local ADDON_NAME, ns = ...

ns.Defaults = {
    profile = {
    general =     {
        themeColor =         {
            [1] = 0,
            [2] = 0.57254904508591,
            [3] = 0.98823535442352,
            [4] = 1,
        },
        themeBgColor = {
            [1] = 0.117,
            [2] = 0.121,
            [3] = 0.133,
            [4] = 1,
        },
        fontOutline = "OUTLINE",
        useClassColorTheme = false,
        font = "Gravity",
        fontSize = 12,
        uiScale = 0.64,
    },
    styling = {
        chatBubbles = {
            enabled = true,
            fontSize = 12,
            fontOutline = "OUTLINE",
        },
        consumableCheckEnabled = true,
        consumableOnReadyCheck = true,
        consumableOnDungeon = true,
        consumableOnRaid = true,
        consumableOnResurrect = false,
        skinReadyCheck = true,
        gamemenu = {
            enabled = true,
            showGravityButton = true,
            buttonFontSize = 14,
        },
        keystone = {
            enabled = true, -- Toggles the skinning
        },
        powerBar = {
            enabled = true,
            position = nil,
        },
        alerts = {
            enabled = true,
            alertPosition = nil,
            alertGrowDirection = "UP",
            toastPosition = nil,
            toastGrowDirection = "DOWN",
        },
        loot = {
            enabled = true,
            position = nil,
            lootUnderMouse = true,
            showTransmogMarkers = true,
        },
        lootRoll = {
            enabled = true,
            position = nil,
            growDirection = "DOWN",
            spacing = 4,
            maxFrames = 4,
        },
        lootResults = {
            enabled = true,
        },
        character = {
            enabled = false,
        },
        objectives = {
            enabled = true,
            width = 260,
            height = 410,
            hideBorder = true,
            moduleFontSize = 14,
            titleFontSize = 13,
            textFontSize = 12,
            moduleColor = { 1, 0.82, 0, 1 },
            titleColor = { 1, 1, 1, 1 },
            textColor = { 0.75, 0.75, 0.75, 1 },
        },
        instanceFrames = {
            enabled = true,
        },
    },
    raidBuffs = {
        enabled = true,
        showOnlyInGroup = true,
        showOnlyInInstance = false,
        providerMode = false,
        hideLabelBar = false,
        iconSize = 32,
        labelFontSize = 12,
        labelTextColor = nil,
        position = nil,
    },
    profileInfo =     {
        created = 0,
        lastModified = 0,
        description = "",
    },
    uiimprovements =     {
        marks =         {
            enabled = true,
            mouseover = true,
            hideBorder = false,
            offsetX = 936,
            spacing = 2,
            useThemeColorBorder = true,
            offsetY = -100,
            borderColor =             {
                [1] = 0,
                [2] = 0,
                [3] = 0,
                [4] = 1,
            },
            size = 26,
        },
        combatExpanded = true,
        character =         {
            inspectEnabled = true,
            statsTextColor =             {
                [1] = 0.953,
                [2] = 0.957,
                [3] = 0.965,
            },
            showInspectItemName = true,
            showInspectGems = true,
            enchantTextColor =             {
                [1] = 0,
                [2] = 0.57254904508591,
                [3] = 0.98823535442352,
                [4] = 1,
            },
            showInspectItemLevel = true,
            showInspectEnchants = true,
            headerColor =             {
                [1] = 0,
                [2] = 0.57254904508591,
                [3] = 0.98823535442352,
                [4] = 1,
            },
            showItemLevel = true,
            showItemName = true,
            headerTextSize = 14,
            showEnchants = true,
            enabled = true,
            panelBgColor =             {
                [1] = 0.1294117718935,
                [2] = 0.1294117718935,
                [3] = 0.1294117718935,
                [4] = 0.85111129283905,
            },
            secondaryStatFormat = "both",
            inspectSlotTextSize = 12,
            noEnchantTextColor =             {
                [1] = 0.5,
                [2] = 0.5,
                [3] = 0.5,
            },
            slotTextSize = 12,
            enchantClassColor = false,
            statsTextSize = 12,
            showTooltips = false,
            panelOpacity = 95,
            inspectPanelScale = 1,
            upgradeTrackColor =             {
                [1] = 0.98,
                [2] = 0.6,
                [3] = 0.35,
                [4] = 1,
            },
            panelScale = 0.85,
            showDurability = false,
            headerClassColor = false,
            showGems = true,
        },
        hideObjectiveTrackerInstanceTypes =         {
            mythicPlus = true,
            mythicDungeon = false,
            normalDungeon = false,
            followerDungeon = false,
            heroicDungeon = false,
            arena = false,
            raid = false,
            pvp = false,
        },
        tooltip =         {
            enabled = true,
            fontSize = 12,
            hideHealthBar = true,
            bgAlpha = 0.8,
            useThemeColor = false,
            showIDs = true,
            bgColor =             {
                [1] = 0,
                [2] = 0,
                [3] = 0,
                [4] = 1,
            },
            customStyle = true,
            anchorToCursor = false,
            combatKey = "SHIFT",
            classColorName = true,
            borderColor =             {
                [1] = 0,
                [2] = 0,
                [3] = 0,
                [4] = 1,
            },
            idColor =             {
                [1] = 1,
                [2] = 1,
                [3] = 1,
                [4] = 1,
            },
            hideInCombat = false,
            visibility =             {
                items = "SHOW",
                abilities = "SHOW",
                npcs = "SHOW",
                customTrackers = "SHOW",
                frames = "SHOW",
                cdm = "SHOW",
            },
            useThemeColorID = true,
        },
        mplusTeleportExpanded = true,
        tooltipExpanded = true,
        skyridingExpanded = true,
        combatTimer =         {
            backdropColor =             {
                [1] = 0,
                [2] = 0,
                [3] = 0,
                [4] = 0.6,
            },
            strata = "BACKGROUND",
            xOffset = 198,
            yOffset = -254,
            borderSize = 1,
            borderColor =             {
                [1] = 0,
                [2] = 0,
                [3] = 0,
                [4] = 1,
            },
            level = 50,
            enabled = true,
            onlyEncounter = false,
            width = 56,
            hideBorder = true,
            showBackdrop = true,
            useThemeColorText = true,
            useThemeColorBorder = true,
            height = 24,
            textAlign = "CENTER",
            fontSize = 14,
            textColor =             {
                [1] = 1,
                [2] = 1,
                [3] = 1,
                [4] = 1,
            },
        },
        autoTurnInQuests = false,
        deleteFix = true,
        autohideExpanded = true,
        buffBordersExpanded = true,
        hideFriendlyNPCNameplates = true,
        buffBorders =         {
            fontSize = 12,
            enableDebuffs = true,
            borderSize = 1,
            enableBuffs = true,
            hideDebuffFrame = false,
            hideBuffFrame = false,
        },
        autoRepairGuild = false,
        automationExpanded = true,
        spellQueueWindow = 120,
        chat =         {
            glass =             {
                bgColor =                 {
                    [1] = 0,
                    [2] = 0,
                    [3] = 0,
                    [4] = 1,
                },
                enabled = true,
                bgAlpha = 0.25,
            },
            hideTabs = true,
            fade =             {
                enabled = false,
                delay = 15,
            },
            copyButtonMode = "hover",
            hideButtons = true,
            urls =             {
                enabled = true,
                color =                 {
                    [1] = 0,
                    [2] = 0.75,
                    [3] = 1,
                    [4] = 1,
                },
            },
            unclamp = true,
            editBox =             {
                enabled = true,
                positionTop = false,
                offsetX = 0,
                bgAlpha = 0.6,
                height = 24,
                offsetY = -5,
                bgColor =                 {
                    [1] = 0,
                    [2] = 0,
                    [3] = 0,
                    [4] = 1,
                },
                width = 476,
            },
            timestamps =             {
                enabled = true,
                format = "24h",
                color =                 {
                    [1] = 0.7607843875885,
                    [2] = 0.77254909276962,
                    [3] = 0.73725491762161,
                    [4] = 1,
                },
            },
        },
        hideRaidWarnings = false,
        autoAcceptQuests = false,
        autoAcceptInvites = "off",
        hideWorldMapBlackout = true,
        worldMarksExpanded = true,
        autoAcceptQuest = true,
        fasterMovieSkip = true,
        chatExpanded = true,
        quickSalvage =         {
            enabled = false,
            modifier = "ALT",
        },
        charExpanded = true,
        autoSellGrey = true,
        showDamageNumbers = true,
        autoRoleAccept = true,
        autoRepair = "personal",
        hideRaidFrameManager = true,
        sellJunk = true,
        hideBuffCollapseButton = true,
        combatTimerExpanded = true,
        hideObjectiveTrackerAlways = false,
        mplusTeleportEnabled = true,
        autoInsertKey = true,
        hideErrorMessages = true,
        autoTurnInQuest = true,
        hideFriendlyPlayerNameplates = true,
    },
    configPanelAlpha = 1,
    minimap =     {
        settingsPreview = false,
        showCraftingOrder = false,
        craftingConfig =         {
            scale = 1,
            offsetY = -24.5,
            point = "TOPRIGHT",
            offsetX = -236.5,
        },
        hideBlizzardBorder = true,
        zoneTextConfig =         {
            colorContested =             {
                [1] = 1,
                [2] = 0.7,
                [3] = 0,
            },
            fontSize = 15,
            allCaps = false,
            useBlizzardZoneColors = false,
            align = "CENTER",
            colorNormal =             {
                [1] = 1,
                [2] = 0.82,
                [3] = 0,
                [4] = 1,
            },
            colorArena =             {
                [1] = 1,
                [2] = 0.1,
                [3] = 0.1,
            },
            colorSanctuary =             {
                [1] = 0.41,
                [2] = 0.8,
                [3] = 0.94,
            },
            font = "Gravity",
            colorHostile =             {
                [1] = 1,
                [2] = 0.1,
                [3] = 0.1,
            },
            offsetX = 0,
            useThemeColor = true,
            colorFriendly =             {
                [1] = 0.1,
                [2] = 1,
                [3] = 0.1,
            },
            offsetY = -1,
            outline = "OUTLINE",
            monochrome = false,
        },
        datatext =         {
            enabled = true,
            fontSize = 12,
            fontColor =             {
                [1] = 1,
                [2] = 1,
                [3] = 1,
                [4] = 1,
            },
            slot1 =             {
                shortLabel = false,
                noLabel = false,
                offsetX = 0,
                offsetY = 0,
                content = "guild",
            },
            bgOpacity = 60,
            useThemeColor = true,
            slot3 =             {
                shortLabel = false,
                noLabel = false,
                offsetX = 0,
                offsetY = 0,
                content = "friends",
            },
            borderSize = 1,
            offsetX = 0,
            borderColor =             {
                [1] = 0,
                [2] = 0,
                [3] = 0,
                [4] = 1,
            },
            height = 25,
            offsetY = 0,
            useThemeColorBorder = false,
            slot2 =             {
                shortLabel = false,
                noLabel = true,
                offsetX = 0,
                offsetY = 0,
                content = "time",
            },
        },
        trackingConfig =         {
            scale = 1,
            offsetY = -0.5,
            point = "TOPRIGHT",
            offsetX = -240,
        },
        lock = true,
        button =         {
            minimapPos = 220,
            hide = false,
        },
        size = 260,
        useThemeColorBorder = false,
        datatextExpanded = true,
        autoZoom = true,
        eyeExpanded = true,
        hideAddonButtons = true,
        showAddonCompartment = false,
        position =         {
            [1] = "TOPRIGHT",
            [2] = "TOPRIGHT",
            [3] = -9.1689233779907,
            [4] = -8.3333225250244,
        },
        fadeElements = true,
        zoomConfig =         {
            scale = 1,
            offsetY = -233,
            point = "TOPRIGHT",
            offsetX = -30.5,
        },
        shape = "SQUARE",
        showDifficulty = true,
        stylingExpanded = true,
        scale = 1,
        showMissions = false,
        borderColor =         {
            [1] = 0,
            [2] = 0,
            [3] = 0,
            [4] = 1,
        },
        clockConfig =         {
            outline = "OUTLINE",
            fontSize = 12,
            point = "TOPRIGHT",
            align = "CENTER",
            monochrome = false,
            timeFormat = "local",
            font = "Gravity",
            offsetX = -116,
            color =             {
                [1] = 1,
                [2] = 1,
                [3] = 1,
                [4] = 1,
            },
            offsetY = -196.5,
            useClassColor = false,
            scale = 1,
        },
        elementsExpanded = true,
        borderSize = 1,
        showZoneText = true,
        mailConfig =         {
            scale = 1,
            offsetY = -240,
            offsetX = -234,
            point = "TOPRIGHT",
        },
        addonCompartmentConfig =         {
            scale = 1,
            offsetY = -113,
            point = "TOPRIGHT",
            offsetX = -1,
        },
        enabled = true,
        showZoomButtons = false,
        showCalendar = false,
        zoneExpanded = true,
        showPing = true,
        difficultyConfig =         {
            scale = 1,
            offsetY = -0.5,
            point = "TOPRIGHT",
            offsetX = 0,
        },
        showCoords = false,
        showTracking = true,
        showAccuracy = false,
        styleExpanded = true,
        calendarConfig =         {
            scale = 1,
            offsetY = -1,
            offsetX = -27.5,
            point = "TOPRIGHT",
        },
        showClock = false,
        showMail = true,
        coordsConfig =         {
            outline = "OUTLINE",
            fontSize = 12,
            point = "TOPRIGHT",
            align = "RIGHT",
            monochrome = false,
            font = "Gravity",
            offsetX = -114,
            color =             {
                [1] = 1,
                [2] = 1,
                [3] = 1,
                [4] = 1,
            },
            offsetY = -235,
            useClassColor = false,
            scale = 1,
        },
        useClassColorBorder = false,
        dungeonEye =         {
            enabled = true,
            corner = "BOTTOMLEFT",
            scale = 1,
            preview = false,
            offsetY = 0,
            offsetX = 1,
        },
        missionsConfig =         {
            scale = 1,
            offsetY = -235,
            point = "TOPRIGHT",
            offsetX = -114,
        },
        generalExpanded = true,
        posExpanded = false,
    },
    fpsBackup =     {
        entityLodDist = "7",
        lodObjectMinSize = "0",
        graphicsProjectedTextures = "1",
        doodadLodScale = "50",
        MSAAQuality = "0",
        LowLatencyMode = "3",
        maxFPSBk = "60",
        spellVisualDensityFilterSetting = "1",
        rippleDetail = "0",
        graphicsLiquidDetail = "1",
        graphicsShadowQuality = "0",
        entityShadowFadeScale = "15",
        graphicsSpellDensity = "0",
        reflectionMode = "0",
        ResampleAlwaysSharpen = "1",
        terrainLodDist = "350",
        Gamma = "1.1",
        OutlineEngineMode = "1",
        vsync = "0",
        cameraDistanceMaxZoomFactor = "2.6",
        lodObjectCullSize = "35",
        lodObjectFadeScale = "50",
        graphicsGroundClutter = "0",
        cameraFov = "90",
        graphicsOutlineMode = "1",
        weatherDensity = "3",
        waterDetail = "1",
        horizonStart = "1000",
        ffxGlow = "0",
        horizonClip = "5000",
        groundEffectDist = "40",
        useTargetFPS = "0",
        ResampleSharpness = "0.2",
        graphicsViewDistance = "3",
        projectedTextures = "1",
        graphicsParticleDensity = "5",
        ffxAntiAliasingMode = "0",
        clusteredShading = "0",
        Contrast = "75",
        Brightness = "50",
        farclip = "5000",
        volumeFogLevel = "0",
        particulatesEnabled = "0",
        targetFPS = "61",
        maxFPS = "144",
        graphicsDepthEffects = "0",
        graphicsSSAO = "0",
        spellClutter = "1",
        GxApi = "D3D12",
        ResampleQuality = "3",
        graphicsComputeEffects = "0",
        graphicsQuality = "9",
        graphicsTextureResolution = "2",
        CameraReduceUnexpectedMovement = "1",
        graphicsEnvironmentDetail = "0",
        TerrainLodDiv = "512",
        physicsLevel = "1",
        textureFilteringMode = "5",
    },
    qol =     {
        autohideExpanded = true,
        hideRaidFrameManager = true,
        autoRepair = "personal",
        combatExpanded = true,
        autoAcceptInvites = "off",
        autoAcceptQuest = true,
        fasterMovieSkip = true,
        spellQueueWindow = 120,
        autoTurnInQuest = true,
        showDamageNumbers = true,
        uiImprovementsExpanded = true,
        convenienceExpanded = true,
        hideErrorMessages = true,
        sellJunk = true,
        hideObjectiveTrackerInstanceTypes =         {
            arena = false,
            mythicDungeon = false,
            normalDungeon = false,
            followerDungeon = false,
            heroicDungeon = false,
            mythicPlus = true,
            raid = false,
            pvp = false,
        },
        hideBuffCollapseButton = true,
        autoRoleAccept = true,
        hideFriendlyPlayerNameplates = true,
        autoInsertKey = true,
        hideFriendlyNPCNameplates = true,
        quickAccessExpanded = true,
        automationExpanded = true,
    },
    datapanels =     {
        extraExpanded = true,
        minimapExpanded = true,
        custom =         {
            ["Panel 1"] =             {
                fontSize = 12,
                fontColor =                 {
                    [1] = 1,
                    [2] = 1,
                    [3] = 1,
                    [4] = 1,
                },
                slots =                 {
                    [1] =                     {
                        content = "durability",
                        shortLabel = true,
                    },
                    [2] =                     {
                        content = "gold",
                        shortLabel = true,
                    },
                    [3] =                     {
                        content = "",
                    },
                },
                borderSize = 0,
                hideLabel = false,
                bgOpacity = 50,
                locked = true,
                enabled = true,
                useThemeColorBorder = true,
                point = "BOTTOMRIGHT",
                width = 250,
                y = 71,
                x = -8,
                name = "Durability",
                useThemeColor = true,
                height = 24,
                borderColor =                 {
                    [1] = 0,
                    [2] = 0.75,
                    [3] = 1,
                    [4] = 1,
                },
                numSlots = 1,
                relativePoint = "BOTTOMRIGHT",
            },
            ["Panel 2"] =             {
                enabled = true,
                fontSize = 12,
                point = "BOTTOMRIGHT",
                height = 24,
                slots =                 {
                    [1] =                     {
                        content = "spec",
                    },
                    [2] =                     {
                        content = "",
                    },
                    [3] =                     {
                        content = "",
                    },
                },
                width = 250,
                y = 47,
                borderSize = 0,
                name = "Spec/Loot",
                bgOpacity = 50,
                locked = true,
                x = -8,
                numSlots = 1,
                relativePoint = "BOTTOMRIGHT",
            },
            ["Panel 3"] =             {
                enabled = true,
                fontSize = 12,
                point = "BOTTOMRIGHT",
                relativePoint = "BOTTOMRIGHT",
                locked = true,
                slots =                 {
                    [1] =                     {
                        content = "gold",
                    },
                    [2] =                     {
                        content = "",
                    },
                    [3] =                     {
                        content = "",
                    },
                },
                width = 250,
                y = 23,
                borderSize = 0,
                name = "Gold",
                bgOpacity = 50,
                height = 24,
                x = -8,
                numSlots = 1,
                hideLabel = false,
            },
            ["Panel 4"] =             {
                enabled = true,
                fontSize = 12,
                point = "TOPRIGHT",
                height = 24,
                slots =                 {
                    [1] =                     {
                        content = "fps",
                    },
                    [2] =                     {
                        content = "ms",
                    },
                    [3] =                     {
                        content = "",
                    },
                },
                width = 120,
                y = -244,
                borderSize = 0,
                name = "FPS/MS",
                bgOpacity = 0,
                locked = true,
                x = -76,
                numSlots = 2,
                relativePoint = "TOPRIGHT",
            },
        },
        customExpanded = true,
    },
    screenindicators =     {
        petWarnings =         {
            enabled = true,
            fontSize = 28,
            xOffset = 0,
            yOffset = -100,
            petDeadWarning = true,
            useThemeColor = true,
            warningColor =             {
                [1] = 1,
                [2] = 1,
                [3] = 1,
                [4] = 1,
            },
            petAttackWarning = true,
            petAttackText = "*** PET NOT ATTACKING ***",
            petDeadText = "*** SUMMON PET ***",
        },
        petWarningsExpanded = true,
        combatStatus =         {
            enabled = true,
            fontSize = 14,
            leaveCombatColor =             {
                [1] = 1,
                [2] = 1,
                [3] = 1,
                [4] = 1,
            },
            fadeTime = 0.3,
            xOffset = 0,
            enterCombatColor =             {
                [1] = 0,
                [2] = 0.57254904508591,
                [3] = 0.98823535442352,
                [4] = 1,
            },
            displayTime = 0.8,
            yOffset = -20,
        },
        cursor =         {
            enabled = true,
            hideOutOfCombat = false,
            reticleSize = 10,
            outCombatAlpha = 1,
            offsetY = 0,
            reticleStyle = "dot",
            hideOnRightClick = false,
            customColor =             {
                [1] = 0,
                [2] = 0.75,
                [3] = 1,
                [4] = 1,
            },
            ringSize = 20,
            gcdReverse = false,
            offsetX = 0,
            useThemeColor = false,
            gcdFadeRing = 0.35,
            gcdEnabled = false,
            ringStyle = "standard",
            inCombatAlpha = 1,
        },
        cursorExpanded = true,
        crosshairExpanded = true,
        enabled = true,
        combatStatusExpanded = true,
        crosshair =         {
            strata = "HIGH",
            borderB = 0,
            customColor =             {
                [1] = 1,
                [2] = 0.949,
                [3] = 0,
                [4] = 1,
            },
            borderSize = 2,
            offsetX = 0,
            changeColorOnRange = true,
            size = 10,
            enabled = false,
            rangeColorInCombatOnly = true,
            outOfRangeColor =             {
                [1] = 1,
                [2] = 0.2,
                [3] = 0.2,
                [4] = 1,
            },
            thickness = 2,
            borderR = 0,
            borderG = 0,
            useThemeColor = true,
            borderA = 1,
            offsetY = 0,
            hideUntilOutOfRange = false,
            onlyInCombat = false,
        },
    },
    main =     {
        showWelcome = true,
        showQuickSettings = true,
    },
    actionbars =     {
        bar5_vis = true,
        bar8_vis = true,
        global =         {
            countFontSize = 14,
            usabilityIndicator = true,
            macroNameFontSize = 10,
            keybindColor =             {
                [1] = 1,
                [2] = 1,
                [3] = 1,
                [4] = 1,
            },
            macroNameOffsetY = 2,
            showKeybinds = true,
            countOffsetY = 2,
            hideEmptyKeybinds = true,
            keybindAnchor = "TOPRIGHT",
            keybindOffsetX = 0,
            hideEmptySlots = false,
            keybindOffsetY = -2,
            showGloss = false,
            showCounts = true,
            countOffsetX = 0,
            showBorders = true,
            countColor =             {
                [1] = 1,
                [2] = 1,
                [3] = 1,
                [4] = 1,
            },
            backdropAlpha = 0.3,
            usabilityDesaturate = false,
            showBackdrop = true,
            macroNameOffsetX = 0,
            countAnchor = "BOTTOMRIGHT",
            macroNameAnchor = "BOTTOM",
            fastUsabilityUpdates = true,
            glossAlpha = 0.6,
            iconZoom = 0.06,
            showMacroNames = true,
            keybindFontSize = 12,
            macroNameColor =             {
                [1] = 1,
                [2] = 1,
                [3] = 1,
                [4] = 1,
            },
        },
        absExpanded = true,
        fadeExpanded = true,
        fade =         {
            enabled = true,
            fadeOutAlpha = 0,
            fadeOutDuration = 0.4,
            linkBars1to8 = false,
            fadeInDuration = 0.2,
            fadeOutDelay = 0.5,
            alwaysShowInCombat = false,
        },
        masterExpanded = true,
        extraExpanded = true,
        enabled = true,
        bars =         {
            bar3 =             {
                alwaysShow = false,
                overrideEnabled = false,
            },
            bar6 =             {
                alwaysShow = false,
                overrideEnabled = false,
            },
            extraActionButton =             {
                alwaysShow = true,
                position =                 {
                    y = 151.46852111816,
                    x = 334.50012207031,
                    point = "BOTTOM",
                    relativePoint = "BOTTOM",
                },
                scale = 1,
                overrideEnabled = false,
                hideArtwork = true,
            },
            bar2 =             {
                alwaysShow = false,
                overrideEnabled = false,
            },
            bar1 =             {
                alwaysShow = true,
                hidePageArrow = true,
                overrideEnabled = false,
            },
            bar8 =             {
                alwaysShow = true,
                overrideEnabled = false,
            },
            bar5 =             {
                alwaysShow = true,
                overrideEnabled = false,
            },
            stance =             {
                alwaysShow = false,
                overrideEnabled = false,
            },
            bar7 =             {
                alwaysShow = false,
                overrideEnabled = false,
            },
            pet =             {
                alwaysShow = false,
                overrideEnabled = false,
            },
            bags =             {
                alwaysShow = false,
                overrideEnabled = false,
            },
            zoneAbility =             {
                alwaysShow = true,
                scale = 1,
                overrideEnabled = false,
                hideArtwork = true,
            },
            microbar =             {
                alwaysShow = false,
                overrideEnabled = false,
            },
            bar4 =             {
                alwaysShow = true,
                overrideEnabled = false,
            },
        },
        bar7_vis = true,
        bar6_vis = true,
    },
    skyriding =     {
        secondWindHeight = 20,
        speedFontSize = 11,
        useThemeColorSecondWind = false,
        rechargeColor =         {
            [1] = 0.40000003576279,
            [2] = 0.90196084976196,
            [3] = 1,
            [4] = 0.60000002384186,
        },
        vigorFontSize = 12,
        showSpeed = true,
        speedFormat = "PERCENT",
        segmentThickness = 1,
        offsetX = -0.000244140625,
        secondWindColor =         {
            [1] = 1,
            [2] = 0.80000007152557,
            [3] = 0.20000001788139,
            [4] = 1,
        },
        locked = false,
        fadeDelay = 1,
        secondWindMode = "MINIBAR",
        width = 286,
        enabled = true,
        fadeDuration = 0.3,
        segmentColor =         {
            [1] = 0,
            [2] = 0,
            [3] = 0,
            [4] = 0.5,
        },
        secondWindScale = 1,
        showSegments = true,
        barTexture = "Gravity v3",
        barColor =         {
            [1] = 0.20000001788139,
            [2] = 0.80000007152557,
            [3] = 1,
            [4] = 1,
        },
        vigorHeight = 20,
        showVigorText = true,
        secondWindBackgroundColor =         {
            [1] = 0.10196079313755,
            [2] = 0.10196079313755,
            [3] = 0.10196079313755,
            [4] = 0.80000001192093,
        },
        vigorTextFormat = "CURRENT",
        backgroundColor =         {
            [1] = 0.10196079313755,
            [2] = 0.10196079313755,
            [3] = 0.10196079313755,
            [4] = 0.80000001192093,
        },
        useThemeColorVigor = true,
        offsetY = -308.33227539062,
        visibility = "AUTO",
        showAbilityIcon = false,
    },
}
}
