local ADDON_NAME, ns = ...
local LSM = LibStub("LibSharedMedia-3.0")
if not LSM then return end

local MediaType = LSM.MediaType
local FONT = MediaType.FONT
local STATUSBAR = MediaType.STATUSBAR
local BACKGROUND = MediaType.BACKGROUND
local BORDER = MediaType.BORDER

-- Dynamic path based on folder name to avoid mismatches
local assetPath = "Interface/AddOns/" .. ADDON_NAME .. "/assets/"

-- ═══════════════════════════════════════════════════════════════
-- FONTS REGISTRATION
-- ═══════════════════════════════════════════════════════════════
LSM:Register(FONT, "Gravity", assetPath .. "Gravity.ttf")
LSM:Register(FONT, "Gravity Big", assetPath .. "Gravity-Big.ttf")
LSM:Register(FONT, "Gravity Bold", assetPath .. "Gravity-Bold.ttf")
LSM:Register(FONT, "Gravity Expressway", assetPath .. "Gravity-Expressway.TTF")
LSM:Register(FONT, "Gravity Light", assetPath .. "Gravity-Light.ttf")
LSM:Register(FONT, "Gravity Regular", assetPath .. "Gravity-Regular.ttf")
LSM:Register(FONT, "Gravity Thin", assetPath .. "Gravity-Thin.ttf")
LSM:Register(FONT, "Gravity Gotham", assetPath .. "Gravity-Gotham.ttf")

-- ═══════════════════════════════════════════════════════════════
-- TEXTURES REGISTRATION
-- ═══════════════════════════════════════════════════════════════
-- Each texture is registered as Background, Statusbar, and Border for maximum flexibility

local function RegisterTexture(name, file)
    local fullPath = assetPath .. file
    LSM:Register(BACKGROUND, name, fullPath)
    LSM:Register(STATUSBAR, name, fullPath)
    LSM:Register(BORDER, name, fullPath)
end

RegisterTexture("Gravity", "Gravity.tga")
RegisterTexture("Gravity 6px", "Gravity6px.tga")
RegisterTexture("Gravity Normal", "Gravity_Normal.tga")
RegisterTexture("Gravity Reverse", "Gravity_reverse.tga")
RegisterTexture("Gravity v2", "Gravity_v2.tga")
RegisterTexture("Gravity v2 Reverse", "Gravity_v2reverse.tga")
RegisterTexture("Gravity v3", "Gravity_v3.tga")
RegisterTexture("Gravity v3 Inverse", "Gravity_v3inverse.tga")
RegisterTexture("Gravity v4", "Gravity_v4.tga")
RegisterTexture("Gravity v4 Inverse", "Gravity_v4inverse.tga")
RegisterTexture("Gravity v5", "Gravity_v5.tga")
RegisterTexture("Gravity v5 Inverse", "Gravity_v5_inverse.tga")
RegisterTexture("Gravity v6", "Gravity_v6.tga")
RegisterTexture("Gravity v6 Inverse", "Gravity_v6inverse.tga")
RegisterTexture("Square", "Square.tga")

-- Special Assets

LSM:Register(STATUSBAR, "GUI Stripes", assetPath .. "absorb_stripe.tga")


-- ═══════════════════════════════════════════════════════════════
-- SOUNDS REGISTRATION
-- ═══════════════════════════════════════════════════════════════
local SOUND = LSM.MediaType.SOUND

LSM:Register(SOUND, "1", assetPath .. "media/sounds/GUI_1.ogg")
LSM:Register(SOUND, "10", assetPath .. "media/sounds/GUI_10.ogg")
LSM:Register(SOUND, "2", assetPath .. "media/sounds/GUI_2.ogg")
LSM:Register(SOUND, "3", assetPath .. "media/sounds/GUI_3.ogg")
LSM:Register(SOUND, "4", assetPath .. "media/sounds/GUI_4.ogg")
LSM:Register(SOUND, "5", assetPath .. "media/sounds/GUI_5.ogg")
LSM:Register(SOUND, "6", assetPath .. "media/sounds/GUI_6.ogg")
LSM:Register(SOUND, "7", assetPath .. "media/sounds/GUI_7.ogg")
LSM:Register(SOUND, "8", assetPath .. "media/sounds/GUI_8.ogg")
LSM:Register(SOUND, "9", assetPath .. "media/sounds/GUI_9.ogg")
LSM:Register(SOUND, "Absorb", assetPath .. "media/sounds/GUI_Absorb.ogg")
LSM:Register(SOUND, "Add", assetPath .. "media/sounds/GUI_Add.ogg")
LSM:Register(SOUND, "Adds", assetPath .. "media/sounds/GUI_Adds.ogg")
LSM:Register(SOUND, "AOE", assetPath .. "media/sounds/GUI_AOE.ogg")
LSM:Register(SOUND, "Assist", assetPath .. "media/sounds/GUI_Assist.ogg")
LSM:Register(SOUND, "Avoid", assetPath .. "media/sounds/GUI_Avoid.ogg")
LSM:Register(SOUND, "Back", assetPath .. "media/sounds/GUI_Back.ogg")
LSM:Register(SOUND, "Backup", assetPath .. "media/sounds/GUI_Backup.ogg")
LSM:Register(SOUND, "Bait", assetPath .. "media/sounds/GUI_Bait.ogg")
LSM:Register(SOUND, "Bark", assetPath .. "media/sounds/GUI_Bark.ogg")
LSM:Register(SOUND, "barrel", assetPath .. "media/sounds/GUI_barrel.ogg")
LSM:Register(SOUND, "Beam", assetPath .. "media/sounds/GUI_Beam.ogg")
LSM:Register(SOUND, "Blade", assetPath .. "media/sounds/GUI_Blade.ogg")
LSM:Register(SOUND, "Bleed", assetPath .. "media/sounds/GUI_Bleed.ogg")
LSM:Register(SOUND, "Bloodlust", assetPath .. "media/sounds/GUI_Bloodlust.ogg")
LSM:Register(SOUND, "Blue", assetPath .. "media/sounds/GUI_Blue.ogg")
LSM:Register(SOUND, "Bombs", assetPath .. "media/sounds/GUI_Bombs.ogg")
LSM:Register(SOUND, "BoP", assetPath .. "media/sounds/GUI_BoP.ogg")
LSM:Register(SOUND, "Boss", assetPath .. "media/sounds/GUI_Boss.ogg")
LSM:Register(SOUND, "Break", assetPath .. "media/sounds/GUI_Break.ogg")
LSM:Register(SOUND, "Buff", assetPath .. "media/sounds/GUI_Buff.ogg")
LSM:Register(SOUND, "Buffed", assetPath .. "media/sounds/GUI_Buffed.ogg")
LSM:Register(SOUND, "Bullet", assetPath .. "media/sounds/GUI_Bullet.ogg")
LSM:Register(SOUND, "Buster", assetPath .. "media/sounds/GUI_Buster.ogg")
LSM:Register(SOUND, "Cage", assetPath .. "media/sounds/GUI_Cage.ogg")
LSM:Register(SOUND, "CC", assetPath .. "media/sounds/GUI_CC.ogg")
LSM:Register(SOUND, "CD", assetPath .. "media/sounds/GUI_CD.ogg")
LSM:Register(SOUND, "Center", assetPath .. "media/sounds/GUI_Center.ogg")
LSM:Register(SOUND, "Chain", assetPath .. "media/sounds/GUI_Chain.ogg")
LSM:Register(SOUND, "chains", assetPath .. "media/sounds/GUI_chains.ogg")
LSM:Register(SOUND, "charge soon", assetPath .. "media/sounds/GUI_charge soon.ogg")
LSM:Register(SOUND, "Charge", assetPath .. "media/sounds/GUI_Charge.ogg")
LSM:Register(SOUND, "Clear", assetPath .. "media/sounds/GUI_Clear.ogg")
LSM:Register(SOUND, "Collect", assetPath .. "media/sounds/GUI_Collect.ogg")
LSM:Register(SOUND, "Cross", assetPath .. "media/sounds/GUI_Cross.ogg")
LSM:Register(SOUND, "Curse", assetPath .. "media/sounds/GUI_Curse.ogg")
LSM:Register(SOUND, "Dance", assetPath .. "media/sounds/GUI_Dance.ogg")
LSM:Register(SOUND, "Debuff", assetPath .. "media/sounds/GUI_Debuff.ogg")
LSM:Register(SOUND, "Defensive", assetPath .. "media/sounds/GUI_Defensive.ogg")
LSM:Register(SOUND, "Disease", assetPath .. "media/sounds/GUI_Disease.ogg")
LSM:Register(SOUND, "Dispell", assetPath .. "media/sounds/GUI_Dispell.ogg")
LSM:Register(SOUND, "Dodge", assetPath .. "media/sounds/GUI_Dodge.ogg")
LSM:Register(SOUND, "dont jump", assetPath .. "media/sounds/GUI_dont jump.ogg")
LSM:Register(SOUND, "Dont Move", assetPath .. "media/sounds/GUI_Dont Move.ogg")
LSM:Register(SOUND, "Dot", assetPath .. "media/sounds/GUI_Dot.ogg")
LSM:Register(SOUND, "DPS", assetPath .. "media/sounds/GUI_DPS.ogg")
LSM:Register(SOUND, "drop", assetPath .. "media/sounds/GUI_drop.ogg")
LSM:Register(SOUND, "Duck", assetPath .. "media/sounds/GUI_Duck.ogg")
LSM:Register(SOUND, "enrage", assetPath .. "media/sounds/GUI_enrage.ogg")
LSM:Register(SOUND, "Enter", assetPath .. "media/sounds/GUI_Enter.ogg")
LSM:Register(SOUND, "Escort", assetPath .. "media/sounds/GUI_Escort.ogg")
LSM:Register(SOUND, "Exit", assetPath .. "media/sounds/GUI_Exit.ogg")
LSM:Register(SOUND, "Feet", assetPath .. "media/sounds/GUI_Feet.ogg")
LSM:Register(SOUND, "Fixate", assetPath .. "media/sounds/GUI_Fixate.ogg")
LSM:Register(SOUND, "Front", assetPath .. "media/sounds/GUI_Front.ogg")
LSM:Register(SOUND, "Frontal", assetPath .. "media/sounds/GUI_Frontal.ogg")
LSM:Register(SOUND, "Gate", assetPath .. "media/sounds/GUI_Gate.ogg")
LSM:Register(SOUND, "Gather", assetPath .. "media/sounds/GUI_Gather.ogg")
LSM:Register(SOUND, "go away", assetPath .. "media/sounds/GUI_go away.ogg")
LSM:Register(SOUND, "Green", assetPath .. "media/sounds/GUI_Green.ogg")
LSM:Register(SOUND, "Healcd", assetPath .. "media/sounds/GUI_Healcd.ogg")
LSM:Register(SOUND, "Hide", assetPath .. "media/sounds/GUI_Hide.ogg")
LSM:Register(SOUND, "High Energy", assetPath .. "media/sounds/GUI_High Energy.ogg")
LSM:Register(SOUND, "High Stacks", assetPath .. "media/sounds/GUI_High Stacks.ogg")
LSM:Register(SOUND, "Immunity", assetPath .. "media/sounds/GUI_Immunity.ogg")
LSM:Register(SOUND, "In", assetPath .. "media/sounds/GUI_In.ogg")
LSM:Register(SOUND, "Info", assetPath .. "media/sounds/GUI_Info.ogg")
LSM:Register(SOUND, "Innervate", assetPath .. "media/sounds/GUI_Innervate.ogg")
LSM:Register(SOUND, "Intermission", assetPath .. "media/sounds/GUI_Intermission.ogg")
LSM:Register(SOUND, "Interrupt", assetPath .. "media/sounds/GUI_Interrupt.ogg")
LSM:Register(SOUND, "Invisibility", assetPath .. "media/sounds/GUI_Invisibility.ogg")
LSM:Register(SOUND, "Jump", assetPath .. "media/sounds/GUI_Jump.ogg")
LSM:Register(SOUND, "Kick", assetPath .. "media/sounds/GUI_Kick.ogg")
LSM:Register(SOUND, "Knock", assetPath .. "media/sounds/GUI_Knock.ogg")
LSM:Register(SOUND, "knockback", assetPath .. "media/sounds/GUI_knockback.ogg")
LSM:Register(SOUND, "Left", assetPath .. "media/sounds/GUI_Left.ogg")
LSM:Register(SOUND, "Link", assetPath .. "media/sounds/GUI_Link.ogg")
LSM:Register(SOUND, "Linked", assetPath .. "media/sounds/GUI_Linked.ogg")
LSM:Register(SOUND, "LoS", assetPath .. "media/sounds/GUI_LoS.ogg")
LSM:Register(SOUND, "Lust", assetPath .. "media/sounds/GUI_Lust.ogg")
LSM:Register(SOUND, "Magic", assetPath .. "media/sounds/GUI_Magic.ogg")
LSM:Register(SOUND, "Mail", assetPath .. "media/sounds/GUI_Mail.ogg")
LSM:Register(SOUND, "Main", assetPath .. "media/sounds/GUI_Main.ogg")
LSM:Register(SOUND, "MC", assetPath .. "media/sounds/GUI_MC.ogg")
LSM:Register(SOUND, "Melee", assetPath .. "media/sounds/GUI_Melee.ogg")
LSM:Register(SOUND, "Move", assetPath .. "media/sounds/GUI_Move.ogg")
LSM:Register(SOUND, "MoveSoon", assetPath .. "media/sounds/GUI_MoveSoon.ogg")
LSM:Register(SOUND, "Next", assetPath .. "media/sounds/GUI_Next.ogg")
LSM:Register(SOUND, "Nuke", assetPath .. "media/sounds/GUI_Nuke.ogg")
LSM:Register(SOUND, "OnYou", assetPath .. "media/sounds/GUI_OnYou.ogg")
LSM:Register(SOUND, "Orange", assetPath .. "media/sounds/GUI_Orange.ogg")
LSM:Register(SOUND, "Orb", assetPath .. "media/sounds/GUI_Orb.ogg")
LSM:Register(SOUND, "Orbs", assetPath .. "media/sounds/GUI_Orbs.ogg")
LSM:Register(SOUND, "Out", assetPath .. "media/sounds/GUI_Out.ogg")
LSM:Register(SOUND, "Overlap", assetPath .. "media/sounds/GUI_Overlap.ogg")
LSM:Register(SOUND, "Pass", assetPath .. "media/sounds/GUI_Pass.ogg")
LSM:Register(SOUND, "personal", assetPath .. "media/sounds/GUI_personal.ogg")
LSM:Register(SOUND, "Phase2", assetPath .. "media/sounds/GUI_Phase2.ogg")
LSM:Register(SOUND, "Phase3", assetPath .. "media/sounds/GUI_Phase3.ogg")
LSM:Register(SOUND, "Physical", assetPath .. "media/sounds/GUI_Physical.ogg")
LSM:Register(SOUND, "PI", assetPath .. "media/sounds/GUI_PI.ogg")
LSM:Register(SOUND, "Poison", assetPath .. "media/sounds/GUI_Poison.ogg")
LSM:Register(SOUND, "Positive", assetPath .. "media/sounds/GUI_Positive.ogg")
LSM:Register(SOUND, "Pots", assetPath .. "media/sounds/GUI_Pots.ogg")
LSM:Register(SOUND, "PS", assetPath .. "media/sounds/GUI_PS.ogg")
LSM:Register(SOUND, "Pull", assetPath .. "media/sounds/GUI_Pull.ogg")
LSM:Register(SOUND, "Purple", assetPath .. "media/sounds/GUI_Purple.ogg")
LSM:Register(SOUND, "Push", assetPath .. "media/sounds/GUI_Push.ogg")
LSM:Register(SOUND, "Range", assetPath .. "media/sounds/GUI_Range.ogg")
LSM:Register(SOUND, "Ready", assetPath .. "media/sounds/GUI_Ready.ogg")
LSM:Register(SOUND, "Red", assetPath .. "media/sounds/GUI_Red.ogg")
LSM:Register(SOUND, "Reflect", assetPath .. "media/sounds/GUI_Reflect.ogg")
LSM:Register(SOUND, "Right", assetPath .. "media/sounds/GUI_Right.ogg")
LSM:Register(SOUND, "Ring", assetPath .. "media/sounds/GUI_Ring.ogg")
LSM:Register(SOUND, "Root", assetPath .. "media/sounds/GUI_Root.ogg")
LSM:Register(SOUND, "run", assetPath .. "media/sounds/GUI_run.ogg")
LSM:Register(SOUND, "Sac", assetPath .. "media/sounds/GUI_Sac.ogg")
LSM:Register(SOUND, "Seed", assetPath .. "media/sounds/GUI_Seed.ogg")
LSM:Register(SOUND, "Selfcd", assetPath .. "media/sounds/GUI_Selfcd.ogg")
LSM:Register(SOUND, "Sentry", assetPath .. "media/sounds/GUI_Sentry.ogg")
LSM:Register(SOUND, "Shield", assetPath .. "media/sounds/GUI_Shield.ogg")
LSM:Register(SOUND, "Side", assetPath .. "media/sounds/GUI_Side.ogg")
LSM:Register(SOUND, "Soak", assetPath .. "media/sounds/GUI_Soak.ogg")
LSM:Register(SOUND, "Soon", assetPath .. "media/sounds/GUI_Soon.ogg")
LSM:Register(SOUND, "Spawn", assetPath .. "media/sounds/GUI_Spawn.ogg")
LSM:Register(SOUND, "Spellsteal", assetPath .. "media/sounds/GUI_Spellsteal.ogg")
LSM:Register(SOUND, "Split", assetPath .. "media/sounds/GUI_Split.ogg")
LSM:Register(SOUND, "Spread", assetPath .. "media/sounds/GUI_Spread.ogg")
LSM:Register(SOUND, "Stack", assetPath .. "media/sounds/GUI_Stack.ogg")
LSM:Register(SOUND, "stop casting", assetPath .. "media/sounds/GUI_stop casting.ogg")
LSM:Register(SOUND, "Stop", assetPath .. "media/sounds/GUI_Stop.ogg")
LSM:Register(SOUND, "Stopcast", assetPath .. "media/sounds/GUI_Stopcast.ogg")
LSM:Register(SOUND, "Swap", assetPath .. "media/sounds/GUI_Swap.ogg")
LSM:Register(SOUND, "Switch", assetPath .. "media/sounds/GUI_Switch.ogg")
LSM:Register(SOUND, "Targeted", assetPath .. "media/sounds/GUI_Targeted.ogg")
LSM:Register(SOUND, "Taunt", assetPath .. "media/sounds/GUI_Taunt.ogg")
LSM:Register(SOUND, "Throw", assetPath .. "media/sounds/GUI_Throw.ogg")
LSM:Register(SOUND, "Thunder", assetPath .. "media/sounds/GUI_Thunder.ogg")
LSM:Register(SOUND, "Totem", assetPath .. "media/sounds/GUI_Totem.ogg")
LSM:Register(SOUND, "Transition", assetPath .. "media/sounds/GUI_Transition.ogg")
LSM:Register(SOUND, "Trap", assetPath .. "media/sounds/GUI_Trap.ogg")
LSM:Register(SOUND, "Turn Away", assetPath .. "media/sounds/GUI_Turn Away.ogg")
LSM:Register(SOUND, "Turn", assetPath .. "media/sounds/GUI_Turn.ogg")
LSM:Register(SOUND, "Wave", assetPath .. "media/sounds/GUI_Wave.ogg")
LSM:Register(SOUND, "Winds", assetPath .. "media/sounds/GUI_Winds.ogg")
LSM:Register(SOUND, "Yellow", assetPath .. "media/sounds/GUI_Yellow.ogg")
LSM:Register(SOUND, "Zone", assetPath .. "media/sounds/GUI_Zone.ogg")
