local ADDON_NAME, ns = ...
local LSM = LibStub("LibSharedMedia-3.0")
if not LSM then return end

local MediaType = LSM.MediaType
local FONT = MediaType.FONT
local STATUSBAR = MediaType.STATUSBAR
local BACKGROUND = MediaType.BACKGROUND
local BORDER = MediaType.BORDER

-- Dynamic path based on folder name to avoid mismatches
local assetPath = "Interface/AddOns/" .. ADDON_NAME .. "/assets/"

-- 
-- FONTS REGISTRATION
-- 
LSM:Register(FONT, "Gravity", assetPath .. "Gravity.ttf")
LSM:Register(FONT, "Gravity ExtraBold", assetPath .. "Gravity-ExtraBold.ttf")
LSM:Register(FONT, "Gravity Bold", assetPath .. "Gravity-Bold.ttf")
LSM:Register(FONT, "Gravity Expressway", assetPath .. "Gravity-Expressway.TTF")
LSM:Register(FONT, "Gravity Light", assetPath .. "Gravity-Light.ttf")
LSM:Register(FONT, "Gravity Regular", assetPath .. "Gravity-Regular.ttf")
LSM:Register(FONT, "Gravity Thin", assetPath .. "Gravity-Thin.ttf")
LSM:Register(FONT, "Gravity Gotham", assetPath .. "Gravity-Gotham.ttf")

-- 
-- TEXTURES REGISTRATION
-- 
-- Each texture is registered as Background, Statusbar, and Border for maximum flexibility

local function RegisterTexture(name, file)
    local fullPath = assetPath .. file
    LSM:Register(BACKGROUND, name, fullPath)
    LSM:Register(STATUSBAR, name, fullPath)
    LSM:Register(BORDER, name, fullPath)
end

RegisterTexture("Gravity", "Gravity.tga")
RegisterTexture("Gravity 6px", "Gravity6px.tga")
RegisterTexture("Gravity Normal", "Gravity_Normal.tga")
RegisterTexture("Gravity Reverse", "Gravity_reverse.tga")
RegisterTexture("Gravity v2", "Gravity_v2.tga")
RegisterTexture("Gravity v2 Reverse", "Gravity_v2reverse.tga")
RegisterTexture("Gravity v3", "Gravity_v3.tga")
RegisterTexture("Gravity v3 Inverse", "Gravity_v3inverse.tga")
RegisterTexture("Gravity v4", "Gravity_v4.tga")
RegisterTexture("Gravity v4 Inverse", "Gravity_v4inverse.tga")
RegisterTexture("Gravity v5", "Gravity_v5.tga")
RegisterTexture("Gravity v5 Inverse", "Gravity_v5_inverse.tga")
RegisterTexture("Gravity v6", "Gravity_v6.tga")
RegisterTexture("Gravity v6 Inverse", "Gravity_v6inverse.tga")
RegisterTexture("Square", "Square.tga")

-- Special Assets

LSM:Register(STATUSBAR, "GUI Stripes", assetPath .. "absorb_stripe.tga")


-- 
-- SOUNDS REGISTRATION
-- 
local SOUND = LSM.MediaType.SOUND

local function RegisterSound(name, file)
    LSM:Register(SOUND, name, assetPath .. "media/sounds/" .. file)
end

RegisterSound("AcousticGuitar", "AcousticGuitar.ogg")
RegisterSound("Adds", "Adds.ogg")
RegisterSound("AirHorn", "AirHorn.ogg")
RegisterSound("Applause", "Applause.ogg")
RegisterSound("Arrow Swoosh", "Arrow_Swoosh.ogg")
RegisterSound("BITE", "BITE.ogg")
RegisterSound("BananaPeelSlip", "BananaPeelSlip.ogg")
RegisterSound("BatmanPunch", "BatmanPunch.ogg")
RegisterSound("BikeHorn", "BikeHorn.ogg")
RegisterSound("Blast", "Blast.ogg")
RegisterSound("Bleat", "Bleat.ogg")
RegisterSound("Boss", "Boss.ogg")
RegisterSound("BoxingArenaSound", "BoxingArenaSound.ogg")
RegisterSound("Brass", "Brass.mp3")
RegisterSound("CartoonVoiceBaritone", "CartoonVoiceBaritone.ogg")
RegisterSound("CartoonWalking", "CartoonWalking.ogg")
RegisterSound("CatMeow2", "CatMeow2.ogg")
RegisterSound("ChickenAlarm", "ChickenAlarm.ogg")
RegisterSound("Circle", "Circle.ogg")
RegisterSound("CowMooing", "CowMooing.ogg")
RegisterSound("Cross", "Cross.ogg")
RegisterSound("Diamond", "Diamond.ogg")
RegisterSound("DontRelease", "DontRelease.ogg")
RegisterSound("DoubleWhoosh", "DoubleWhoosh.ogg")
RegisterSound("Drums", "Drums.ogg")
RegisterSound("ESPARK1", "ESPARK1.ogg")
RegisterSound("Empowered", "Empowered.ogg")
RegisterSound("ErrorBeep", "ErrorBeep.ogg")
RegisterSound("Fireball", "Fireball.ogg")
RegisterSound("Focus", "Focus.ogg")
RegisterSound("Gasp", "Gasp.ogg")
RegisterSound("Glass", "Glass.mp3")
RegisterSound("GoatBleating", "GoatBleating.ogg")
RegisterSound("HeartbeatSingle", "HeartbeatSingle.ogg")
RegisterSound("Idiot", "Idiot.ogg")
RegisterSound("KittenMeow", "KittenMeow.ogg")
RegisterSound("Left", "Left.ogg")
RegisterSound("Moon", "Moon.ogg")
RegisterSound("Next", "Next.ogg")
RegisterSound("OhNo", "OhNo.ogg")
RegisterSound("PUNCH", "PUNCH.ogg")
RegisterSound("Portal", "Portal.ogg")
RegisterSound("Protected", "Protected.ogg")
RegisterSound("Release", "Release.ogg")
RegisterSound("Right", "Right.ogg")
RegisterSound("RingingPhone", "RingingPhone.ogg")
RegisterSound("RoaringLion", "RoaringLion.ogg")
RegisterSound("RobotBlip", "RobotBlip.ogg")
RegisterSound("RoosterChickenCalls", "RoosterChickenCalls.ogg")
RegisterSound("RunAway", "RunAway.ogg")
RegisterSound("SharpPunch", "SharpPunch.ogg")
RegisterSound("SheepBleat", "SheepBleat.ogg")
RegisterSound("Shotgun", "Shotgun.ogg")
RegisterSound("Skull", "Skull.ogg")
RegisterSound("Spread", "Spread.ogg")
RegisterSound("Square", "Square.ogg")
RegisterSound("SqueakyToyShort", "SqueakyToyShort.ogg")
RegisterSound("Squeakypig", "Squeakypig.ogg")
RegisterSound("SquishFart", "SquishFart.ogg")
RegisterSound("Stack", "Stack.ogg")
RegisterSound("Star", "Star.ogg")
RegisterSound("Switch", "Switch.ogg")
RegisterSound("SynthChord", "SynthChord.ogg")
RegisterSound("TadaFanfare", "TadaFanfare.ogg")
RegisterSound("Taunt", "Taunt.ogg")
RegisterSound("TempleBellHuge", "TempleBellHuge.ogg")
RegisterSound("Torch", "Torch.ogg")
RegisterSound("Triangle", "Triangle.ogg")
RegisterSound("WarningSiren", "WarningSiren.ogg")
RegisterSound("WaterDrop", "WaterDrop.ogg")
RegisterSound("Xylophone", "Xylophone.ogg")
RegisterSound("Aggro", "aggro.ogg")
RegisterSound("Bam", "bam.ogg")
RegisterSound("Bear Polar", "bear_polar.ogg")
RegisterSound("Big Kiss", "big_kiss.ogg")
RegisterSound("Burp 4", "burp4.ogg")
RegisterSound("Cat 2", "cat2.ogg")
RegisterSound("Chant 2", "chant2.ogg")
RegisterSound("Chant 4", "chant4.ogg")
RegisterSound("Chimes", "chimes.ogg")
RegisterSound("Cookie", "cookie.ogg")
RegisterSound("Heartbeat", "heartbeat.ogg")
RegisterSound("Hic 3", "hic3.ogg")
RegisterSound("Huh 1", "huh_1.ogg")
RegisterSound("Hurricane", "hurricane.ogg")
RegisterSound("Hyena", "hyena.ogg")
RegisterSound("Kaching", "kaching.ogg")
RegisterSound("Moan", "moan.ogg")
RegisterSound("Panther 1", "panther1.ogg")
RegisterSound("Phone", "phone.ogg")
RegisterSound("Rain on Roof", "rainroof.ogg")
RegisterSound("Rocket", "rocket.ogg")
RegisterSound("Ships Whistle", "shipswhistle.ogg")
RegisterSound("Shot", "shot.ogg")
RegisterSound("Snake Attack", "snakeatt.ogg")
RegisterSound("Sneeze", "sneeze.ogg")
RegisterSound("Sonar", "sonar.ogg")
RegisterSound("Splash", "splash.ogg")
RegisterSound("Sword Echo", "swordecho.ogg")
RegisterSound("Throw Knife", "throwknife.ogg")
RegisterSound("Thunder", "thunder.ogg")
RegisterSound("Wicked Male Laugh 1", "wickedmalelaugh1.ogg")
RegisterSound("Wilhelm", "wilhelm.ogg")
RegisterSound("Wlaugh", "wlaugh.ogg")
RegisterSound("Wolf 5", "wolf5.ogg")
RegisterSound("Yeehaw", "yeehaw.ogg")



RegisterSound("10", "10.ogg")
RegisterSound("6", "6.ogg")
RegisterSound("7", "7.ogg")
RegisterSound("8", "8.ogg")
RegisterSound("9", "9.ogg")
RegisterSound("Absorb", "Absorb.ogg")
RegisterSound("Add", "Add.ogg")
RegisterSound("AoE", "AoE.ogg")
RegisterSound("Avoid", "Avoid.ogg")
RegisterSound("Bait", "Bait.ogg")
RegisterSound("Beam", "Beam.ogg")
RegisterSound("Behind", "Behind.ogg")
RegisterSound("bigkiss", "bigkiss.ogg")
RegisterSound("Bloodlust", "Bloodlust.ogg")
RegisterSound("Bomb", "Bomb.ogg")
RegisterSound("Breath", "Breath.ogg")
RegisterSound("Buff", "Buff.ogg")
RegisterSound("CC", "CC.ogg")
RegisterSound("Charge", "Charge.ogg")
RegisterSound("Clear", "Clear.ogg")
RegisterSound("ClearIn", "ClearIn.ogg")
RegisterSound("Collect", "Collect.ogg")
RegisterSound("Combat", "Combat.ogg")
RegisterSound("Dance", "Dance.ogg")
RegisterSound("Debuff", "Debuff.ogg")
RegisterSound("Destroy", "Destroy.ogg")
RegisterSound("Dispell", "Dispell.ogg")
RegisterSound("Dodge", "Dodge.ogg")
RegisterSound("DodgeInc", "DodgeInc.ogg")
RegisterSound("Dot", "Dot.ogg")
RegisterSound("External", "External.ogg")
RegisterSound("Fixate", "Fixate.ogg")
RegisterSound("Freedom", "Freedom.ogg")
RegisterSound("Frontal", "Frontal.ogg")
RegisterSound("Green", "Green.ogg")
RegisterSound("Hide", "Hide.ogg")
RegisterSound("HighStacks", "HighStacks.ogg")
RegisterSound("Immune", "Immune.ogg")
RegisterSound("In", "In.ogg")
RegisterSound("Inc", "Inc.ogg")
RegisterSound("Inside", "Inside.ogg")
RegisterSound("Intermission", "Intermission.ogg")
RegisterSound("Kick", "Kick.ogg")
RegisterSound("Knock", "Knock.ogg")
RegisterSound("Linked", "Linked.ogg")
RegisterSound("LoS", "LoS.ogg")
RegisterSound("Melee", "Melee.ogg")
RegisterSound("Mount", "Mount.ogg")
RegisterSound("Move", "Move.ogg")
RegisterSound("Nuke", "Nuke.ogg")
RegisterSound("Orb", "Orb.ogg")
RegisterSound("Orbs", "Orbs.ogg")
RegisterSound("Out", "Out.ogg")
RegisterSound("Outrange", "Outrange.ogg")
RegisterSound("Personal", "Personal.ogg")
RegisterSound("Pot", "Pot.ogg")
RegisterSound("Pull", "Pull.ogg")
RegisterSound("Push", "Push.ogg")
RegisterSound("Ranged", "Ranged.ogg")
RegisterSound("Ready", "Ready.ogg")
RegisterSound("Red", "Red.ogg")
RegisterSound("Reflect", "Reflect.ogg")
RegisterSound("Run", "Run.ogg")
RegisterSound("Sac", "Sac.ogg")
RegisterSound("Shield", "Shield.ogg")
RegisterSound("Soak", "Soak.ogg")
RegisterSound("Spike", "Spike.ogg")
RegisterSound("Stop", "Stop.ogg")
RegisterSound("StopCast", "StopCast.ogg")
RegisterSound("Totem", "Totem.ogg")
RegisterSound("Trap", "Trap.ogg")
RegisterSound("Turn", "Turn.ogg")
